--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.FACEBOOK_ADS.VW_CHANGES_TO_CD2_AD AS

WITH SRC_AD AS
(SELECT
  'FP-' || ID             AS AD_ID
 ,NAME                    AS AD_NM
 ,BID_AMOUNT              AS BID_AMT
 ,BID_TYPE                AS BID_TYPE_DC
 ,CREATED_TIME::DATETIME  AS CREATED_DTTM
 ,STATUS                  AS STATUS_DC
 FROM FACEBOOK_ADS.ADS
 )
 
 ,DM_AD AS
(SELECT
  AD_ID                   AS AD_ID
 ,AD_NM                   AS AD_NM
 ,BID_AMT                 AS BID_AMT
 ,BID_TYPE_DC             AS BID_TYPE_DC
 ,CREATED_DTTM::DATETIME  AS CREATED_DTTM
 ,STATUS_DC               AS STATUS_DC
 ,CURR_REC_IND            AS CURR_REC_IND
 FROM DM_ADS.CD2_AD
 WHERE CURR_REC_IND = 'Y'
   AND SUBSTR(AD_ID,1,2) = 'FP'
)

-- PULL ALL SOURCE RECORDS WHERE DATA ON THE ROW HAS CHANGED AND MARK THE ROW AS 'UPDATE'
SELECT
 'UPDATE'      AS ROW_CHANGE_DC
,A.AD_ID
,A.AD_NM
,A.BID_AMT
,A.BID_TYPE_DC
,A.CREATED_DTTM
,A.STATUS_DC
FROM SRC_AD        AS A
JOIN DM_AD         AS B ON         A.AD_ID         = B.AD_ID
                           AND (   A.AD_NM        <> B.AD_NM
                                OR A.BID_AMT      <> B.BID_AMT
                                OR A.BID_TYPE_DC  <> B.BID_TYPE_DC
                                OR A.CREATED_DTTM <> B.CREATED_DTTM
                                OR A.STATUS_DC    <> B.STATUS_DC)
WHERE B.CURR_REC_IND = 'Y'

UNION

-- PULL ALL SOURCE RECORDS WHERE DATA ON THE ROW IS NEW AND MARK THE ROW AS 'APPEND'
SELECT
 'APPEND'                AS ROW_CHANGE_DC
,AD_ID
,AD_NM
,BID_AMT
,BID_TYPE_DC
,CREATED_DTTM::DATETIME  AS CREATED_DTTM
,STATUS_DC
FROM SRC_AD
WHERE AD_ID NOT IN (SELECT AD_ID
                    FROM DM_AD)
 
UNION

-- PULL ALL DIMENSION RECORDS WHERE THE RECORD NO LONG EXISTS IN SOURCE AND MARK THE ROW AS 'FINAL'
SELECT
 'FINAL'       AS ROW_CHANGE_DC
,AD_ID
,AD_NM
,BID_AMT
,BID_TYPE_DC
,CREATED_DTTM
,STATUS_DC
FROM DM_AD
WHERE CURR_REC_IND = 'Y'
  AND AD_ID NOT IN (SELECT AD_ID
                    FROM SRC_AD);

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.FACEBOOK_ADS.VW_CHANGES_TO_CD2_ADSET AS

WITH SRC_ADSET AS
(SELECT
 'FP-' || ID              AS ADSET_ID
,NAME                     AS ADSET_NM
,EFFECTIVE_STATUS         AS STATUS_DC
,DAILY_BUDGET             AS DAILY_BUDGET_AMT
,LIFETIME_BUDGET          AS LIFETIME_BUDGET_AMT
,BUDGET_REMAINING         AS BUDGET_REMAINING_AMT
,TARGETING::VARCHAR(8000) AS TARGETING_ARRAY
,START_TIME::DATETIME     AS START_DTTM
,END_TIME::DATETIME       AS END_DTTM
,CREATED_TIME::DATETIME   AS CREATED_DTTM
,UPDATED_TIME::DATETIME   AS UPDATED_DTTM
 FROM FACEBOOK_ADS.ADSETS
 )
 
 ,DM_ADSET AS
(SELECT
 ADSET_ID
,ADSET_NM
,STATUS_DC
,DAILY_BUDGET_AMT
,LIFETIME_BUDGET_AMT
,BUDGET_REMAINING_AMT
,TARGETING_ARRAY
,START_DTTM
,END_DTTM
,CREATED_DTTM
,UPDATED_DTTM
,CURR_REC_IND
 FROM DM_ADS.CD2_ADSET
 WHERE CURR_REC_IND = 'Y'
   AND SUBSTR(ADSET_ID,1,2) = 'FP'
)
 
-- PULL ALL SOURCE RECORDS WHERE DATA ON THE ROW HAS CHANGED AND MARK THE ROW AS 'UPDATE'
SELECT
 'UPDATE'               AS ROW_CHANGE_DC
,A.ADSET_ID
,A.ADSET_NM
,A.STATUS_DC
,A.DAILY_BUDGET_AMT
,A.LIFETIME_BUDGET_AMT
,A.BUDGET_REMAINING_AMT
,A.TARGETING_ARRAY
,A.START_DTTM
,A.END_DTTM
,A.CREATED_DTTM
,A.UPDATED_DTTM
FROM SRC_ADSET         AS A
JOIN DM_ADSET          AS B ON         A.ADSET_ID              = B.ADSET_ID
                               AND (   A.ADSET_NM             <> B.ADSET_NM
                                    OR A.STATUS_DC            <> B.STATUS_DC
                                    OR A.DAILY_BUDGET_AMT     <> B.DAILY_BUDGET_AMT
                                    OR A.LIFETIME_BUDGET_AMT  <> B.LIFETIME_BUDGET_AMT
                                    OR A.BUDGET_REMAINING_AMT <> B.BUDGET_REMAINING_AMT
                                    OR A.START_DTTM           <> B.START_DTTM
                                    OR A.END_DTTM             <> B.END_DTTM
                                    OR A.TARGETING_ARRAY      <> B.TARGETING_ARRAY
                                    OR A.CREATED_DTTM         <> B.CREATED_DTTM
                                    OR A.UPDATED_DTTM         <> B.UPDATED_DTTM)
WHERE B.CURR_REC_IND = 'Y'

UNION

-- PULL ALL SOURCE RECORDS WHERE DATA ON THE ROW IS NEW AND MARK THE ROW AS 'APPEND'
SELECT
 'APPEND'               AS ROW_CHANGE_DC
,ADSET_ID
,ADSET_NM
,STATUS_DC
,DAILY_BUDGET_AMT
,LIFETIME_BUDGET_AMT
,BUDGET_REMAINING_AMT
,TARGETING_ARRAY
,START_DTTM
,END_DTTM
,CREATED_DTTM
,UPDATED_DTTM
FROM SRC_ADSET
WHERE ADSET_ID NOT IN (SELECT ADSET_ID
                       FROM DM_ADSET)
 
UNION

-- PULL ALL DIMENSION RECORDS WHERE THE RECORD NO LONG EXISTS IN SOURCE AND MARK THE ROW AS 'FINAL' 
SELECT
 'FINAL'                AS ROW_CHANGE_DC
,ADSET_ID
,ADSET_NM
,STATUS_DC
,DAILY_BUDGET_AMT
,LIFETIME_BUDGET_AMT
,BUDGET_REMAINING_AMT
,TARGETING_ARRAY
,START_DTTM
,END_DTTM
,CREATED_DTTM
,UPDATED_DTTM
FROM DM_ADSET
WHERE CURR_REC_IND = 'Y'
  AND ADSET_ID NOT IN (SELECT ADSET_ID
                       FROM SRC_ADSET);

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.FACEBOOK_ADS.VW_CHANGES_TO_CD2_CAMPAIGN AS

WITH SRC_CAMPAIGN AS
(SELECT
 'FP-' || ID             AS CAMPAIGN_ID
,NAME                    AS CAMPAIGN_NM
,EFFECTIVE_STATUS        AS STATUS_DC
,BUYING_TYPE             AS BUYING_TYPE_DC
,START_TIME::DATETIME    AS START_DTTM
,OBJECTIVE               AS OBJECTIVE_DC
 FROM FACEBOOK_ADS.CAMPAIGNS
 )
 
 ,DM_CAMPAIGN AS
(SELECT
  CAMPAIGN_ID
 ,CAMPAIGN_NM
 ,STATUS_DC
 ,BUYING_TYPE_DC
 ,START_DTTM
 ,OBJECTIVE_DC
 ,CURR_REC_IND
 FROM DM_ADS.CD2_CAMPAIGN
 WHERE CURR_REC_IND = 'Y'
   AND SUBSTR(CAMPAIGN_ID,1,2) = 'FP'
)
 
-- PULL ALL SOURCE RECORDS WHERE DATA ON THE ROW HAS CHANGED AND MARK THE ROW AS 'UPDATE'
SELECT
 'UPDATE'          AS ROW_CHANGE_DC
,A.CAMPAIGN_ID
,A.CAMPAIGN_NM
,A.STATUS_DC
,A.BUYING_TYPE_DC
,A.START_DTTM
,A.OBJECTIVE_DC
FROM SRC_CAMPAIGN      AS A
JOIN DM_CAMPAIGN       AS B ON         A.CAMPAIGN_ID           = B.CAMPAIGN_ID
                               AND (   A.CAMPAIGN_NM          <> B.CAMPAIGN_NM
                                    OR A.STATUS_DC            <> B.STATUS_DC
                                    OR A.BUYING_TYPE_DC       <> B.BUYING_TYPE_DC
                                    OR A.START_DTTM           <> B.START_DTTM
                                    OR A.OBJECTIVE_DC         <> B.OBJECTIVE_DC)
WHERE B.CURR_REC_IND = 'Y'
  AND SUBSTR(B.CAMPAIGN_ID,1,2) = 'FP'

UNION

-- PULL ALL SOURCE RECORDS WHERE DATA ON THE ROW IS NEW AND MARK THE ROW AS 'APPEND'
SELECT
 'APPEND'               AS ROW_CHANGE_DC
,CAMPAIGN_ID
,CAMPAIGN_NM
,STATUS_DC
,BUYING_TYPE_DC
,START_DTTM
,OBJECTIVE_DC
FROM SRC_CAMPAIGN
WHERE CAMPAIGN_ID NOT IN (SELECT CAMPAIGN_ID
                          FROM DM_CAMPAIGN
                          WHERE CURR_REC_IND = 'Y'
                            AND SUBSTR(CAMPAIGN_ID,1,2) = 'FP'
                         )
 
UNION
 
-- PULL ALL DIMENSION RECORDS WHERE THE RECORD NO LONG EXISTS IN SOURCE AND MARK THE ROW AS 'FINAL' 
SELECT
 'FINAL'                AS ROW_CHANGE_DC
,CAMPAIGN_ID
,CAMPAIGN_NM
,STATUS_DC
,BUYING_TYPE_DC
,START_DTTM
,OBJECTIVE_DC
FROM DM_CAMPAIGN
WHERE CURR_REC_IND = 'Y'
  AND CAMPAIGN_ID NOT IN (SELECT CAMPAIGN_ID
                          FROM SRC_CAMPAIGN
                          WHERE CURR_REC_IND = 'Y'
                            AND SUBSTR(CAMPAIGN_ID,1,2) = 'FP'
                         );

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.FACEBOOK_ADS.VW_CHANGES_TO_CD2_CREATIVE(
	ROW_CHANGE_DC,
	CREATIVE_ID,
	CREATIVE_NM,
	ACTOR_ID,
	BODY_TXT,
	CALL_TO_ACTION_TYPE_DC,
	OBJECT_TYPE_DC,
	STATUS_DC,
	TITLE_TXT
) AS

WITH SRC_CREATIVE AS
(SELECT
 'FP-' || ID             AS CREATIVE_ID
,NAME                    AS CREATIVE_NM
,ACTOR_ID                AS ACTOR_ID
,BODY                    AS BODY_TXT
,CALL_TO_ACTION_TYPE     AS CALL_TO_ACTION_TYPE_DC
,OBJECT_TYPE             AS OBJECT_TYPE_DC
,STATUS                  AS STATUS_DC
,TITLE                   AS TITLE_TXT
 FROM FACEBOOK_ADS.ADCREATIVE
 )
 
 ,DM_CREATIVE AS
(SELECT
  CREATIVE_ID
 ,CREATIVE_NM
 ,ACTOR_ID
 ,BODY_TXT
 ,CALL_TO_ACTION_TYPE_DC
 ,OBJECT_TYPE_DC
 ,STATUS_DC
 ,TITLE_TXT
 ,CURR_REC_IND
 FROM DM_ADS.CD2_CREATIVE
 WHERE CURR_REC_IND = 'Y'
   AND SUBSTR(CREATIVE_ID,1,2) = 'FP'
)

-- PULL ALL SOURCE RECORDS WHERE DATA ON THE ROW HAS CHANGED AND MARK THE ROW AS 'UPDATE'
SELECT
 'UPDATE'                  AS ROW_CHANGE_DC
,A.CREATIVE_ID
,A.CREATIVE_NM
,A.ACTOR_ID
,A.BODY_TXT
,A.CALL_TO_ACTION_TYPE_DC
,A.OBJECT_TYPE_DC
,A.STATUS_DC
,A.TITLE_TXT
FROM SRC_CREATIVE      AS A
JOIN DM_CREATIVE       AS B ON         A.CREATIVE_ID             = B.CREATIVE_ID
                               AND (   A.CREATIVE_NM            <> B.CREATIVE_NM
                                    OR A.ACTOR_ID               <> B.ACTOR_ID
                                    OR A.BODY_TXT               <> B.BODY_TXT
                                    OR A.CALL_TO_ACTION_TYPE_DC <> B.CALL_TO_ACTION_TYPE_DC
                                    OR A.OBJECT_TYPE_DC         <> B.OBJECT_TYPE_DC
                                    OR A.STATUS_DC              <> B.STATUS_DC
                                    OR A.TITLE_TXT              <> B.TITLE_TXT)
WHERE B.CURR_REC_IND = 'Y'

UNION

-- PULL ALL SOURCE RECORDS WHERE DATA ON THE ROW IS NEW AND MARK THE ROW AS 'APPEND'
SELECT
 'APPEND'               AS ROW_CHANGE_DC
,CREATIVE_ID
,CREATIVE_NM
,ACTOR_ID
,BODY_TXT
,CALL_TO_ACTION_TYPE_DC
,OBJECT_TYPE_DC
,STATUS_DC
,TITLE_TXT
FROM SRC_CREATIVE
WHERE CREATIVE_ID NOT IN (SELECT CREATIVE_ID
                          FROM DM_CREATIVE)
 
UNION
 
-- PULL ALL DIMENSION RECORDS WHERE THE RECORD NO LONG EXISTS IN SOURCE AND MARK THE ROW AS 'FINAL' 
SELECT
 'FINAL'                AS ROW_CHANGE_DC
,CREATIVE_ID
,CREATIVE_NM
,ACTOR_ID
,BODY_TXT
,CALL_TO_ACTION_TYPE_DC
,OBJECT_TYPE_DC
,STATUS_DC
,TITLE_TXT
FROM DM_CREATIVE
WHERE CURR_REC_IND = 'Y'
  AND CREATIVE_ID NOT IN (SELECT CREATIVE_ID
                          FROM SRC_CREATIVE);
--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.FACEBOOK_ADS.VW_FS_ADS_AGE_AND_GENDER AS

WITH SRC_ADS_AG AS
(SELECT DISTINCT
-- FOREIGN KEYS
 'FP-' || AD_ID                      AS AD_ID
,'FP-' || ADSET_ID                   AS ADSET_ID
,'FP-' || CAMPAIGN_ID                AS CAMPAIGN_ID
,AGE                                 AS AGE_RANGE_DC
,GENDER                              AS GENDER_DC
-- ARRAYS
,ACTIONS::VARCHAR(8000)                             AS ACTION_ARRAY
,OUTBOUND_CLICKS::VARCHAR(8000)                     AS OUTBOUND_CLICK_ARRAY
,UNIQUE_ACTIONS::VARCHAR(8000)                      AS UNIQUE_ACTION_ARRAY
,UNIQUE_OUTBOUND_CLICKS::VARCHAR(8000)              AS UNIQUE_OUTBOUND_CLICK_ARRAY
,WEBSITE_CTR::VARCHAR(8000)                         AS WEBSITE_CLICK_THROUGH_ARRAY
,VIDEO_30_SEC_WATCHED_ACTIONS::VARCHAR(8000)        AS VIDEO_30_SEC_WATCHED_ACTION_ARRAY
,VIDEO_P25_WATCHED_ACTIONS::VARCHAR(8000)           AS VIDEO_P25_WATCHED_ACTION_ARRAY
,VIDEO_P50_WATCHED_ACTIONS::VARCHAR(8000)           AS VIDEO_P50_WATCHED_ACTION_ARRAY
,VIDEO_P100_WATCHED_ACTIONS::VARCHAR(8000)          AS VIDEO_P100_WATCHED_ACTION_ARRAY
,VIDEO_P75_WATCHED_ACTIONS::VARCHAR(8000)           AS VIDEO_P75_WATCHED_ACTION_ARRAY
-- METRICS
,CLICKS                              AS CLICK_QTY
,COST_PER_INLINE_LINK_CLICK          AS PER_INLINE_LINK_CLICK_COST_AMT
,COST_PER_INLINE_POST_ENGAGEMENT     AS PER_INLINE_POST_ENGAGEMENT_COST_AMT
,COST_PER_UNIQUE_CLICK               AS PER_UNIQUE_CLICK_COST_AMT
,COST_PER_UNIQUE_INLINE_LINK_CLICK   AS PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT
,CPC                                 AS AVERAGE_CPC_COST_AMT
,CPM                                 AS AVERAGE_CPM_COST_AMT
,CPP                                 AS PER_POINT_COST_AMT
,CTR                                 AS CLICK_THROUGH_RATE_AMT
,DATE_START                          AS START_DTTM
,DATE_STOP                           AS STOP_DTTM
,FREQUENCY                           AS FREQUENCY_QTY
,IMPRESSIONS                         AS IMPRESSIONS_QTY
,INLINE_LINK_CLICKS                  AS INLINE_LINK_CLICK_QTY
,INLINE_LINK_CLICK_CTR               AS INLINE_LINK_CLICK_THROUGH_PCT
,INLINE_POST_ENGAGEMENT              AS INLINE_POST_ENGAGEMENT_QTY
,OBJECTIVE                           AS OBJECTIVE_DC
,REACH                               AS REACH_QTY
,SPEND                               AS SPEND_QTY
,UNIQUE_CLICKS                       AS UNIQUE_CLICK_QTY
,UNIQUE_CTR                          AS UNIQUE_CLICK_THROUGH_PCT
,UNIQUE_INLINE_LINK_CLICKS           AS UNIQUE_INLINE_LINK_CLICK_QTY
,UNIQUE_INLINE_LINK_CLICK_CTR        AS UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT
,UNIQUE_LINK_CLICKS_CTR              AS UNIQUE_LINK_CLICK_THROUGH_PCT
FROM FACEBOOK_ADS.ADS_INSIGHTS_AGE_AND_GENDER
)

SELECT
 C.CD2_AD_ID                                        AS CD2_AD_ID
,D.CD2_ADSET_ID                                     AS CD2_ADSET_ID
,E.CD2_CAMPAIGN_ID                                  AS CD2_CAMPAIGN_ID
,A.AGE_RANGE_DC                                     AS AGE_RANGE_DC
,A.GENDER_DC                                        AS GENDER_DC
,CURRENT_DATE || ' ' || CURRENT_TIME                AS LOAD_DTTM
,A.START_DTTM::DATETIME                             AS START_DTTM
,A.STOP_DTTM::DATETIME                              AS STOP_DTTM
,A.ACTION_ARRAY                                     AS ACTION_ARRAY
,A.OUTBOUND_CLICK_ARRAY                             AS OUTBOUND_CLICK_ARRAY
,A.UNIQUE_ACTION_ARRAY                              AS UNIQUE_ACTION_ARRAY
,A.UNIQUE_OUTBOUND_CLICK_ARRAY                      AS UNIQUE_OUTBOUND_CLICK_ARRAY
,A.WEBSITE_CLICK_THROUGH_ARRAY                      AS WEBSITE_CLICK_THROUGH_ARRAY
,A.VIDEO_30_SEC_WATCHED_ACTION_ARRAY                AS VIDEO_30_SEC_WATCHED_ACTION_ARRAY
,A.VIDEO_P25_WATCHED_ACTION_ARRAY                   AS VIDEO_P25_WATCHED_ACTION_ARRAY
,A.VIDEO_P50_WATCHED_ACTION_ARRAY                   AS VIDEO_P50_WATCHED_ACTION_ARRAY
,A.VIDEO_P100_WATCHED_ACTION_ARRAY                  AS VIDEO_P100_WATCHED_ACTION_ARRAY
,A.VIDEO_P75_WATCHED_ACTION_ARRAY                   AS VIDEO_P75_WATCHED_ACTION_ARRAY
,IFNULL(A.CLICK_QTY, 0)                             AS CLICK_QTY
,IFNULL(A.PER_INLINE_LINK_CLICK_COST_AMT, 0)        AS PER_INLINE_LINK_CLICK_COST_AMT
,IFNULL(A.PER_INLINE_POST_ENGAGEMENT_COST_AMT, 0)   AS PER_INLINE_POST_ENGAGEMENT_COST_AMT
,IFNULL(A.PER_UNIQUE_CLICK_COST_AMT, 0)             AS PER_UNIQUE_CLICK_COST_AMT
,IFNULL(A.PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT, 0) AS PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT
,IFNULL(A.AVERAGE_CPC_COST_AMT, 0)                  AS AVERAGE_CPC_COST_AMT
,IFNULL(A.AVERAGE_CPM_COST_AMT, 0)                  AS AVERAGE_CPM_COST_AMT
,IFNULL(A.PER_POINT_COST_AMT, 0)                    AS PER_POINT_COST_AMT
,IFNULL(A.CLICK_THROUGH_RATE_AMT, 0)                AS CLICK_THROUGH_RATE_AMT
,IFNULL(A.FREQUENCY_QTY, 0)                         AS FREQUENCY_QTY
,IFNULL(A.IMPRESSIONS_QTY, 0)                       AS IMPRESSIONS_QTY
,IFNULL(A.INLINE_LINK_CLICK_QTY, 0)                 AS INLINE_LINK_CLICK_QTY
,IFNULL(A.INLINE_LINK_CLICK_THROUGH_PCT, 0)         AS INLINE_LINK_CLICK_THROUGH_PCT
,IFNULL(A.INLINE_POST_ENGAGEMENT_QTY, 0)            AS INLINE_POST_ENGAGEMENT_QTY
,A.OBJECTIVE_DC                                     AS OBJECTIVE_DC
,IFNULL(A.REACH_QTY, 0)                             AS REACH_QTY
,IFNULL(A.SPEND_QTY, 0)                             AS SEND_QTY
,IFNULL(A.UNIQUE_CLICK_QTY, 0)                      AS UNIQUE_CLICK_QTY
,IFNULL(A.UNIQUE_CLICK_THROUGH_PCT, 0)              AS UNIQUE_CLICK_THROUGH_PCT
,IFNULL(A.UNIQUE_INLINE_LINK_CLICK_QTY, 0)          AS UNIQUE_INLINE_LINK_CLICK_QTY
,IFNULL(A.UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT, 0)  AS UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT
,IFNULL(A.UNIQUE_LINK_CLICK_THROUGH_PCT, 0)         AS UNIQUE_LINK_CLICK_THROUGH_PCT
FROM SRC_ADS_AG                AS A
JOIN DM_ADS.CD2_AD             AS C ON     A.AD_ID          = C.AD_ID
                                       AND C.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_ADSET          AS D ON     A.ADSET_ID       = D.ADSET_ID
                                       AND D.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_CAMPAIGN       AS E ON     A.CAMPAIGN_ID    = E.CAMPAIGN_ID
                                       AND E.CURR_REC_IND   = 'Y';

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.FACEBOOK_ADS.VW_FS_ADS_COUNTRY AS

WITH SRC_ADS_COUNTRY AS
(SELECT DISTINCT
-- FOREIGN KEYS
 'FP-' || AD_ID                                        AS AD_ID
,'FP-' || ADSET_ID                                     AS ADSET_ID
,'FP-' || CAMPAIGN_ID                                  AS CAMPAIGN_ID
,COUNTRY                                               AS COUNTRY_ARRAY
,DATE_START                                            AS START_DTTM
,DATE_STOP                                             AS STOP_DTTM
-- ARRAYS
,ACTIONS::VARCHAR(8000)                                               AS ACTION_ARRAY
,OUTBOUND_CLICKS::VARCHAR(8000)                                       AS OUTBOUND_CLICK_ARRAY
,UNIQUE_ACTIONS::VARCHAR(8000)                                        AS UNIQUE_ACTION_ARRAY
,UNIQUE_OUTBOUND_CLICKS::VARCHAR(8000)                                AS UNIQUE_OUTBOUND_CLICK_ARRAY
,WEBSITE_CTR::VARCHAR(8000)                                           AS WEBSITE_CLICK_THROUGH_ARRAY
,VIDEO_30_SEC_WATCHED_ACTIONS::VARCHAR(8000)                          AS VIDEO_30_SEC_WATCHED_ACTION_ARRAY
,VIDEO_P100_WATCHED_ACTIONS::VARCHAR(8000)                            AS VIDEO_P100_WATCHED_ACTION_ARRAY
,VIDEO_P25_WATCHED_ACTIONS::VARCHAR(8000)                             AS VIDEO_P25_WATCHED_ACTION_ARRAY
,VIDEO_P50_WATCHED_ACTIONS::VARCHAR(8000)                             AS VIDEO_P50_WATCHED_ACTION_ARRAY
,VIDEO_P75_WATCHED_ACTIONS::VARCHAR(8000)                             AS VIDEO_P75_WATCHED_ACTION_ARRAY
-- METRICS
,CLICKS                                                AS CLICK_QTY
,COST_PER_INLINE_LINK_CLICK                            AS PER_INLINE_LINK_CLICK_COST_AMT
,COST_PER_INLINE_POST_ENGAGEMENT                       AS PER_INLINE_POST_ENGAGEMENT_COST_AMT
,COST_PER_UNIQUE_CLICK                                 AS PER_UNIQUE_CLICK_COST_AMT
,COST_PER_UNIQUE_INLINE_LINK_CLICK                     AS PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT
,CPC                                                   AS PER_CLICK_AVERAGE_COST_AMT
,CPM                                                   AS PER_THOUSAND_IMPRESSIONS_AVERAGE_COST_AMT
,CPP                                                   AS PER_POINT_COST_AMT
,CTR                                                   AS CLICK_THROUGH_PCT
,FREQUENCY                                             AS FREQUENCY_QTY
,IMPRESSIONS                                           AS IMPRESSIONS_QTY
,INLINE_LINK_CLICKS                                    AS INLINE_LINK_CLICK_QTY
,INLINE_LINK_CLICK_CTR                                 AS INLINE_LINK_CLICK_THROUGH_PCT
,INLINE_POST_ENGAGEMENT                                AS INLINE_POST_ENGAGEMENT_QTY
,OBJECTIVE                                             AS OBJECTIVE_DC
,REACH                                                 AS REACH_QTY
,SPEND                                                 AS SPEND_AMT
,UNIQUE_CLICKS                                         AS UNIQUE_CLICK_QTY
,UNIQUE_CTR                                            AS UNIQUE_CLICK_THROUGH_PCT
,UNIQUE_INLINE_LINK_CLICKS                             AS UNIQUE_INLINE_LINK_CLICK_QTY
,UNIQUE_INLINE_LINK_CLICK_CTR                          AS UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT
,UNIQUE_LINK_CLICKS_CTR                                AS UNIQUE_LINK_CLICK_THROUGH_PCT
FROM FACEBOOK_ADS.ADS_INSIGHTS_COUNTRY
)

SELECT
 C.CD2_AD_ID                                           AS CD2_AD_ID
,D.CD2_ADSET_ID                                        AS CD2_ADSET_ID
,E.CD2_CAMPAIGN_ID                                     AS CD2_CAMPAIGN_ID
,A.COUNTRY_ARRAY                                       AS COUNTRY_ARRAY
,CURRENT_DATE || ' ' || CURRENT_TIME                   AS LOAD_DTTM
,A.START_DTTM::DATETIME                                AS START_DTTM
,A.STOP_DTTM::DATETIME                                 AS STOP_DTTM
,A.ACTION_ARRAY                                        AS ACTION_ARRAY
,A.OUTBOUND_CLICK_ARRAY                                AS OUTBOUND_CLICK_ARRAY
,A.UNIQUE_ACTION_ARRAY                                 AS UNIQUE_ACTION_ARRAY
,A.UNIQUE_OUTBOUND_CLICK_ARRAY                         AS UNIQUE_OUTBOUND_CLICK_ARRAY
,A.VIDEO_30_SEC_WATCHED_ACTION_ARRAY                   AS VIDEO_30_SEC_WATCHED_ACTION_ARRAY
,A.VIDEO_P100_WATCHED_ACTION_ARRAY                     AS VIDEO_P100_WATCHED_ACTION_ARRAY
,A.VIDEO_P25_WATCHED_ACTION_ARRAY                      AS VIDEO_P25_WATCHED_ACTION_ARRAY
,A.VIDEO_P50_WATCHED_ACTION_ARRAY                      AS VIDEO_P50_WATCHED_ACTION_ARRAY
,A.VIDEO_P75_WATCHED_ACTION_ARRAY                      AS VIDEO_P75_WATCHED_ACTION_ARRAY
,A.WEBSITE_CLICK_THROUGH_ARRAY                         AS WEBSITE_CLICK_THROUGH_ARRAY

,IFNULL(A.CLICK_QTY,0)                                 AS CLICK_QTY
,IFNULL(A.PER_INLINE_LINK_CLICK_COST_AMT,0)            AS PER_INLINE_LINK_CLICK_COST_AMT
,IFNULL(A.PER_INLINE_POST_ENGAGEMENT_COST_AMT,0)       AS PER_INLINE_POST_ENGAGEMENT_COST_AMT
,IFNULL(A.PER_UNIQUE_CLICK_COST_AMT,0)                 AS PER_UNIQUE_CLICK_COST_AMT
,IFNULL(A.PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT,0)     AS PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT
,IFNULL(A.PER_CLICK_AVERAGE_COST_AMT,0)                AS PER_CLICK_AVERAGE_COST_AMT
,IFNULL(A.PER_THOUSAND_IMPRESSIONS_AVERAGE_COST_AMT,0) AS PER_THOUSAND_IMPRESSIONS_AVERAGE_COST_AMT
,IFNULL(A.PER_POINT_COST_AMT,0)                        AS PER_POINT_COST_AMT
,IFNULL(A.CLICK_THROUGH_PCT,0)                         AS CLICK_THROUGH_PCT
,IFNULL(A.FREQUENCY_QTY,0)                             AS FREQUENCY_QTY
,IFNULL(A.IMPRESSIONS_QTY,0)                           AS IMPRESSIONS_QTY
,IFNULL(A.INLINE_LINK_CLICK_QTY,0)                     AS INLINE_LINK_CLICK_QTY
,IFNULL(A.INLINE_LINK_CLICK_THROUGH_PCT,0)             AS INLINE_LINK_CLICK_THROUGH_PCT
,IFNULL(A.INLINE_POST_ENGAGEMENT_QTY,0)                AS INLINE_POST_ENGAGEMENT_QTY
,A.OBJECTIVE_DC                                        AS OBJECTIVE_DC
,IFNULL(A.REACH_QTY,0)                                 AS REACH_QTY
,IFNULL(A.SPEND_AMT,0)                                 AS SPEND_AMT
,IFNULL(A.UNIQUE_CLICK_QTY,0)                          AS UNIQUE_CLICK_QTY
,IFNULL(A.UNIQUE_CLICK_THROUGH_PCT,0)                  AS UNIQUE_CLICK_THROUGH_PCT
,IFNULL(A.UNIQUE_INLINE_LINK_CLICK_QTY,0)              AS UNIQUE_INLINE_LINK_CLICK_QTY
,IFNULL(A.UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT,0)      AS UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT
,IFNULL(A.UNIQUE_LINK_CLICK_THROUGH_PCT,0)             AS UNIQUE_LINK_CLICK_THROUGH_PCT

FROM SRC_ADS_COUNTRY                                   AS A
JOIN DM_ADS.CD2_AD                                     AS C ON     A.AD_ID          = C.AD_ID
																AND C.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_ADSET                                  AS D ON     A.ADSET_ID       = D.ADSET_ID
																AND D.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_CAMPAIGN                               AS E ON     A.CAMPAIGN_ID    = E.CAMPAIGN_ID
																AND E.CURR_REC_IND   = 'Y';

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.FACEBOOK_ADS.VW_FS_ADS_DMA AS

WITH SRC_ADS_DMA AS
(SELECT DISTINCT
-- FOREIGN KEYS
 'FP-' || AD_ID                      AS AD_ID
,'FP-' || ADSET_ID                   AS ADSET_ID
,'FP-' || CAMPAIGN_ID                AS CAMPAIGN_ID
,DMA                                 AS DMA_ARRAY
,DATE_START                          AS START_DTTM
,DATE_STOP                           AS STOP_DTTM
-- ARRAYS
,ACTIONS::VARCHAR(8000)                             AS ACTION_ARRAY
,OUTBOUND_CLICKS::VARCHAR(8000)                     AS OUTBOUND_CLICK_ARRAY
,UNIQUE_ACTIONS::VARCHAR(8000)                      AS UNIQUE_ACTION_ARRAY
,UNIQUE_OUTBOUND_CLICKS::VARCHAR(8000)              AS UNIQUE_OUTBOUND_CLICK_ARRAY
,WEBSITE_CTR::VARCHAR(8000)                         AS WEBSITE_CLICK_THROUGH_ARRAY
-- METRICS
,CLICKS                              AS CLICK_QTY
,COST_PER_INLINE_LINK_CLICK          AS PER_INLINE_LINK_CLICK_AVERAGE_COST_AMT
,COST_PER_INLINE_POST_ENGAGEMENT     AS PER_INLINE_POST_ENGAGEMENT_AVERAGE_COST_AMT
,CPC                                 AS PER_CLICK_COST_AMT
,CPM                                 AS PER_THOUSAND_IMPRESSIONS_COST_AMT
,CTR                                 AS CLICK_THROUGH_PCT
,FREQUENCY                           AS FREQUENCY_QTY
,IMPRESSIONS                         AS IMPRESSIONS_QTY
,INLINE_LINK_CLICKS                  AS INLINE_LINK_CLICK_QTY
,INLINE_POST_ENGAGEMENT              AS INLINE_POST_ENGAGEMENT_QTY
,OBJECTIVE                           AS OBJECTIVE_DC
,REACH                               AS REACH_QTY
,SPEND                               AS SPEND_QTY
,UNIQUE_CLICKS                       AS UNIQUE_CLICK_QTY
FROM FACEBOOK_ADS.ADS_INSIGHTS_DMA
)

SELECT
 C.CD2_AD_ID                                             AS CD2_AD_ID
,D.CD2_ADSET_ID                                          AS CD2_ADSET_ID
,E.CD2_CAMPAIGN_ID                                       AS CD2_CAMPAIGN_ID
,A.DMA_ARRAY                                             AS DMA_ARRAY
,CURRENT_DATE || ' ' || CURRENT_TIME                     AS LOAD_DTTM
,A.START_DTTM::DATETIME                                  AS START_DTTM
,A.STOP_DTTM::DATETIME                                   AS STOP_DTTM
,A.ACTION_ARRAY                                          AS ACTION_ARRAY
,A.OUTBOUND_CLICK_ARRAY                                  AS OUTBOUND_CLICK_ARRAY
,A.UNIQUE_ACTION_ARRAY                                   AS UNIQUE_ACTION_ARRAY
,A.UNIQUE_OUTBOUND_CLICK_ARRAY                           AS UNIQUE_OUTBOUND_CLICK_ARRAY
,A.WEBSITE_CLICK_THROUGH_ARRAY                           AS WEBSITE_CLICK_THROUGH_ARRAY
,IFNULL(A.CLICK_QTY,0)                                   AS CLICK_QTY
,IFNULL(A.PER_INLINE_LINK_CLICK_AVERAGE_COST_AMT,0)      AS PER_INLINE_LINK_CLICK_AVERAGE_COST_AMT
,IFNULL(A.PER_INLINE_POST_ENGAGEMENT_AVERAGE_COST_AMT,0) AS PER_INLINE_POST_ENGAGEMENT_AVERAGE_COST_AMT
,IFNULL(A.PER_CLICK_COST_AMT,0)                          AS PER_CLICK_COST_AMT
,IFNULL(A.PER_THOUSAND_IMPRESSIONS_COST_AMT,0)           AS PER_THOUSAND_IMPRESSIONS_COST_AMT
,IFNULL(A.CLICK_THROUGH_PCT,0)                           AS CLICK_THROUGH_PCT
,IFNULL(A.FREQUENCY_QTY,0)                               AS FREQUENCY_QTY
,IFNULL(A.IMPRESSIONS_QTY,0)                             AS IMPRESSIONS_QTY
,IFNULL(A.INLINE_LINK_CLICK_QTY,0)                       AS INLINE_LINK_CLICK_QTY
,IFNULL(A.INLINE_POST_ENGAGEMENT_QTY,0)                  AS INLINE_POST_ENGAGEMENT_QTY
,A.OBJECTIVE_DC                                          AS OBJECTIVE_DC
,IFNULL(A.REACH_QTY,0)                                   AS REACH_QTY
,IFNULL(A.SPEND_QTY,0)                                   AS SPEND_AMT
,IFNULL(A.UNIQUE_CLICK_QTY,0)                            AS UNIQUE_CLICK_QTY
FROM SRC_ADS_DMA               AS A
JOIN DM_ADS.CD2_AD             AS C ON     A.AD_ID          = C.AD_ID
										AND C.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_ADSET          AS D ON     A.ADSET_ID       = D.ADSET_ID
										AND D.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_CAMPAIGN       AS E ON     A.CAMPAIGN_ID    = E.CAMPAIGN_ID
										AND E.CURR_REC_IND   = 'Y';

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.FACEBOOK_ADS.VW_FS_ADS_HOURLY_ADVERTISER AS

WITH SRC_ADS_HRADV AS
(SELECT DISTINCT
-- FOREIGN KEYS
 'FP-' || AD_ID                                     AS AD_ID
,'FP-' || ADSET_ID                                  AS ADSET_ID
,'FP-' || CAMPAIGN_ID                               AS CAMPAIGN_ID
,HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE    AS TIME_RANGE_DC
-- ARRAYS
,ACTIONS::VARCHAR(8000)                             AS ACTION_ARRAY
,OUTBOUND_CLICKS::VARCHAR(8000)                     AS OUTBOUND_CLICK_ARRAY
,WEBSITE_CTR::VARCHAR(8000)                         AS WEBSITE_CLICK_THROUGH_ARRAY
-- METRICS
,ACCOUNT_CURRENCY                                   AS CURRENCY_CD
,BUYING_TYPE                                        AS BUYING_TYPE_DC
,CLICKS                                             AS CLICK_QTY
,COST_PER_INLINE_LINK_CLICK                         AS PER_INLINE_LINK_CLICK_COST_AMT
,COST_PER_INLINE_POST_ENGAGEMENT                    AS PER_INLINE_POST_ENGAGEMENT_COST_AMT
,CPC                                                AS AVERAGE_CPC_COST_AMT
,CPM                                                AS AVERAGE_CPM_COST_AMT
,CTR                                                AS CLICK_THROUGH_PCT
,DATE_START                                         AS START_DTTM
,DATE_STOP                                          AS STOP_DTTM
,IMPRESSIONS                                        AS IMPRESSIONS_QTY
,INLINE_LINK_CLICKS                                 AS INLINE_LINK_CLICK_QTY
,INLINE_LINK_CLICK_CTR                              AS INLINE_LINK_CLICK_THROUGH_PCT
,INLINE_POST_ENGAGEMENT                             AS INLINE_POST_ENGAGEMENT_QTY
,OBJECTIVE                                          AS OBJECTIVE_DC
,SPEND                                              AS SPEND_QTY
FROM FACEBOOK_ADS.ADS_INSIGHTS_HOURLY_ADVERTISER
)

SELECT
 C.CD2_AD_ID                                        AS CD2_AD_ID
,D.CD2_ADSET_ID                                     AS CD2_ADSET_ID
,E.CD2_CAMPAIGN_ID                                  AS CD2_CAMPAIGN_ID
,A.TIME_RANGE_DC                                    AS TIME_RANGE_DC
,CURRENT_DATE || ' ' || CURRENT_TIME                AS LOAD_DTTM
,A.START_DTTM::DATETIME                             AS START_DTTM
,A.STOP_DTTM::DATETIME                              AS STOP_DTTM
,A.ACTION_ARRAY                                     AS ACTION_ARRAY
,A.OUTBOUND_CLICK_ARRAY                             AS OUTBOUND_CLICK_ARRAY
,A.WEBSITE_CLICK_THROUGH_ARRAY                      AS WEBSITE_CLICK_THROUGH_ARRAY
,A.CURRENCY_CD                                      AS ACCOUNT_CURRENCY_CD
,A.BUYING_TYPE_DC                                   AS BUYING_TYPE_DC
,IFNULL(A.CLICK_QTY, 0)                             AS CLICK_QTY
,IFNULL(A.PER_INLINE_LINK_CLICK_COST_AMT, 0)        AS PER_INLINE_LINK_CLICK_COST_AMT
,IFNULL(A.PER_INLINE_POST_ENGAGEMENT_COST_AMT, 0)   AS PER_INLINE_POST_ENGAGEMENT_COST_AMT
,IFNULL(A.AVERAGE_CPC_COST_AMT, 0)                  AS AVERAGE_CPC_COST_AMT
,IFNULL(A.AVERAGE_CPM_COST_AMT, 0)                  AS AVERAGE_CPM_COST_AMT
,IFNULL(A.CLICK_THROUGH_PCT, 0)                     AS CLICK_THROUGH_RATE_AMT
,IFNULL(A.IMPRESSIONS_QTY, 0)                       AS IMPRESSIONS_QTY
,IFNULL(A.INLINE_LINK_CLICK_QTY, 0)                 AS INLINE_LINK_CLICK_QTY
,IFNULL(A.INLINE_LINK_CLICK_THROUGH_PCT, 0)         AS INLINE_LINK_CLICK_THROUGH_PCT
,IFNULL(A.INLINE_POST_ENGAGEMENT_QTY, 0)            AS INLINE_POST_ENGAGEMENT_QTY
,A.OBJECTIVE_DC                                     AS OBJECTIVE_DC
,IFNULL(A.SPEND_QTY, 0)                             AS SEND_QTY
FROM SRC_ADS_HRADV             AS A
JOIN DM_ADS.CD2_AD             AS C ON     A.AD_ID          = C.AD_ID
                                       AND C.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_ADSET          AS D ON     A.ADSET_ID       = D.ADSET_ID
                                       AND D.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_CAMPAIGN       AS E ON     A.CAMPAIGN_ID    = E.CAMPAIGN_ID
                                       AND E.CURR_REC_IND   = 'Y';

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.FACEBOOK_ADS.VW_FS_ADS_PLATFORM_AND_DEVICE AS

WITH SRC_ADS_PLATFORM AS
(SELECT DISTINCT
-- FOREIGN KEYS
  'FP-' || AD_ID                      AS AD_ID
,'FP-' || ADSET_ID                   AS ADSET_ID
,'FP-' || CAMPAIGN_ID                AS CAMPAIGN_ID
,PLATFORM_POSITION                   AS POSITION_DC
,PUBLISHER_PLATFORM                  AS PLATFORM_DC
,IMPRESSION_DEVICE                   AS DEVICE_DC
,DATE_START                          AS START_DTTM
,DATE_STOP                           AS STOP_DTTM
 -- ARRAYS
,ACTIONS::VARCHAR(8000)                             AS ACTION_ARRAY
,OUTBOUND_CLICKS::VARCHAR(8000)                     AS OUTBOUND_CLICK_ARRAY
,UNIQUE_ACTIONS::VARCHAR(8000)                      AS UNIQUE_ACTION_ARRAY
,UNIQUE_OUTBOUND_CLICKS::VARCHAR(8000)              AS UNIQUE_OUTBOUND_CLICK_ARRAY
,WEBSITE_CTR::VARCHAR(8000)                         AS WEBSITE_CLICK_THROUGH_ARRAY
,VIDEO_30_SEC_WATCHED_ACTIONS::VARCHAR(8000)        AS VIDEO_30_SEC_WATCHED_ACTION_ARRAY
,VIDEO_P25_WATCHED_ACTIONS::VARCHAR(8000)           AS VIDEO_P25_WATCHED_ACTION_ARRAY
,VIDEO_P50_WATCHED_ACTIONS::VARCHAR(8000)           AS VIDEO_P50_WATCHED_ACTION_ARRAY
--,VIDEO_P100_WATCHED_ACTIONS::VARCHAR(8000)          AS VIDEO_P100_WATCHED_ACTION_ARRAY
,VIDEO_P75_WATCHED_ACTIONS::VARCHAR(8000)           AS VIDEO_P75_WATCHED_ACTION_ARRAY
-- METRICS
,CLICKS                              AS CLICK_QTY
,COST_PER_INLINE_LINK_CLICK          AS PER_INLINE_LINK_CLICK_COST_AMT
,COST_PER_INLINE_POST_ENGAGEMENT     AS PER_INLINE_POST_ENGAGEMENT_COST_AMT
,COST_PER_UNIQUE_CLICK               AS PER_UNIQUE_CLICK_COST_AMT
,COST_PER_UNIQUE_INLINE_LINK_CLICK   AS PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT
,CPC                                 AS AVERAGE_CPC_COST_AMT
,CPM                                 AS AVERAGE_CPM_COST_AMT
,CPP                                 AS PER_POINT_COST_AMT
,CTR                                 AS CLICK_THROUGH_RATE_AMT
,FREQUENCY                           AS FREQUENCY_QTY
,IMPRESSIONS                         AS IMPRESSIONS_QTY
,INLINE_LINK_CLICKS                  AS INLINE_LINK_CLICK_QTY
,INLINE_LINK_CLICK_CTR               AS INLINE_LINK_CLICK_THROUGH_PCT
,INLINE_POST_ENGAGEMENT              AS INLINE_POST_ENGAGEMENT_QTY
,OBJECTIVE                           AS OBJECTIVE_DC
,REACH                               AS REACH_QTY
,SPEND                               AS SPEND_QTY
,UNIQUE_CLICKS                       AS UNIQUE_CLICK_QTY
,UNIQUE_CTR                          AS UNIQUE_CLICK_THROUGH_PCT
,UNIQUE_INLINE_LINK_CLICK_CTR        AS UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT
,UNIQUE_INLINE_LINK_CLICKS           AS UNIQUE_INLINE_LINK_CLICK_QTY
,UNIQUE_LINK_CLICKS_CTR              AS UNIQUE_LINK_CLICK_THROUGH_PCT
FROM FACEBOOK_ADS.ADS_INSIGHTS_PLATFORM_AND_DEVICE
)

SELECT
 C.CD2_AD_ID                                        AS CD2_AD_ID
,D.CD2_ADSET_ID                                     AS CD2_ADSET_ID
,E.CD2_CAMPAIGN_ID                                  AS CD2_CAMPAIGN_ID
,A.POSITION_DC                                      AS POSITION_DC
,A.PLATFORM_DC                                      AS PLATFORM_DC
,A.DEVICE_DC                                        AS DEVICE_DC
,CURRENT_DATE || ' ' || CURRENT_TIME                AS LOAD_DTTM
,A.START_DTTM::DATETIME                             AS START_DTTM
,A.STOP_DTTM::DATETIME                              AS STOP_DTTM
,A.ACTION_ARRAY                                     AS ACTION_ARRAY
,A.OUTBOUND_CLICK_ARRAY                             AS OUTBOUND_CLICK_ARRAY
,A.UNIQUE_ACTION_ARRAY                              AS UNIQUE_ACTION_ARRAY
,A.UNIQUE_OUTBOUND_CLICK_ARRAY                      AS UNIQUE_OUTBOUND_CLICK_ARRAY
,A.VIDEO_30_SEC_WATCHED_ACTION_ARRAY                AS VIDEO_30_SEC_WATCHED_ACTION_ARRAY
,A.VIDEO_P25_WATCHED_ACTION_ARRAY                   AS VIDEO_P25_WATCHED_ACTION_ARRAY
,A.VIDEO_P50_WATCHED_ACTION_ARRAY                   AS VIDEO_P50_WATCHED_ACTION_ARRAY
--,A.VIDEO_P100_WATCHED_ACTION_ARRAY                  AS VIDEO_P100_WATCHED_ACTION_ARRAY
,A.VIDEO_P75_WATCHED_ACTION_ARRAY                   AS VIDEO_P75_WATCHED_ACTION_ARRAY
,A.WEBSITE_CLICK_THROUGH_ARRAY                      AS WEBSITE_CLICK_THROUGH_ARRAY
,IFNULL(A.CLICK_QTY, 0)                             AS CLICK_QTY
,IFNULL(A.PER_INLINE_LINK_CLICK_COST_AMT, 0)        AS PER_INLINE_LINK_CLICK_COST_AMT
,IFNULL(A.PER_INLINE_POST_ENGAGEMENT_COST_AMT, 0)   AS PER_INLINE_POST_ENGAGEMENT_COST_AMT
,IFNULL(A.PER_UNIQUE_CLICK_COST_AMT, 0)             AS PER_UNIQUE_CLICK_COST_AMT
,IFNULL(A.PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT, 0) AS PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT
,IFNULL(A.AVERAGE_CPC_COST_AMT, 0)                  AS AVERAGE_CPC_COST_AMT
,IFNULL(A.AVERAGE_CPM_COST_AMT, 0)                  AS AVERAGE_CPM_COST_AMT
,IFNULL(A.PER_POINT_COST_AMT, 0)                    AS PER_POINT_COST_AMT
,IFNULL(A.CLICK_THROUGH_RATE_AMT, 0)                AS CLICK_THROUGH_RATE_AMT
,IFNULL(A.FREQUENCY_QTY, 0)                         AS FREQUENCY_QTY
,IFNULL(A.IMPRESSIONS_QTY, 0)                       AS IMPRESSIONS_QTY
,IFNULL(A.INLINE_LINK_CLICK_QTY, 0)                 AS INLINE_LINK_CLICK_QTY
,IFNULL(A.INLINE_LINK_CLICK_THROUGH_PCT, 0)         AS INLINE_LINK_CLICK_THROUGH_PCT
,IFNULL(A.INLINE_POST_ENGAGEMENT_QTY, 0)            AS INLINE_POST_ENGAGEMENT_QTY
,A.OBJECTIVE_DC                                     AS OBJECTIVE_DC
,IFNULL(A.REACH_QTY, 0)                             AS REACH_QTY
,IFNULL(A.SPEND_QTY, 0)                             AS SEND_QTY
,IFNULL(A.UNIQUE_CLICK_QTY, 0)                      AS UNIQUE_CLICK_QTY
,IFNULL(A.UNIQUE_CLICK_THROUGH_PCT, 0)              AS UNIQUE_CLICK_THROUGH_PCT
,IFNULL(A.UNIQUE_INLINE_LINK_CLICK_QTY, 0)          AS UNIQUE_INLINE_LINK_CLICK_QTY
,IFNULL(A.UNIQUE_LINK_CLICK_THROUGH_PCT, 0)         AS UNIQUE_LINK_CLICK_THROUGH_PCT
,IFNULL(A.UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT, 0)  AS UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT
FROM SRC_ADS_PLATFORM          AS A
JOIN DM_ADS.CD2_AD             AS C ON     A.AD_ID          = C.AD_ID
                                       AND C.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_ADSET          AS D ON     A.ADSET_ID       = D.ADSET_ID
                                       AND D.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_CAMPAIGN       AS E ON     A.CAMPAIGN_ID    = E.CAMPAIGN_ID
                                       AND E.CURR_REC_IND   = 'Y';

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.FACEBOOK_ADS.VW_FS_ADS_REGION AS

WITH SRC_ADS_REGION AS
(SELECT DISTINCT
-- FOREIGN KEYS
 'FP-' || AD_ID                                     AS AD_ID
,'FP-' || ADSET_ID                                  AS ADSET_ID
,'FP-' || CAMPAIGN_ID                               AS CAMPAIGN_ID
,REGION                                             AS REGION_DC
,DATE_START                                         AS START_DTTM
,DATE_STOP                                          AS STOP_DTTM
 -- ARRAYS
,ACTIONS::VARCHAR(8000)                             AS ACTION_ARRAY
,OUTBOUND_CLICKS::VARCHAR(8000)                     AS OUTBOUND_CLICK_ARRAY
,UNIQUE_ACTIONS::VARCHAR(8000)                      AS UNIQUE_ACTION_ARRAY
,UNIQUE_OUTBOUND_CLICKS::VARCHAR(8000)              AS UNIQUE_OUTBOUND_CLICK_ARRAY
,WEBSITE_CTR::VARCHAR(8000)                         AS WEBSITE_CLICK_THROUGH_ARRAY
-- METRICS
,CPC                                                AS AVERAGE_CPC_COST_AMT
,CPM                                                AS AVERAGE_CPM_COST_AMT
,CLICKS                                             AS CLICK_QTY
,CPP                                                AS PER_POINT_COST_AMT
,CTR                                                AS CLICK_THROUGH_RATE_AMT
,FREQUENCY                                          AS FREQUENCY_QTY
,IMPRESSIONS                                        AS IMPRESSIONS_QTY
,INLINE_LINK_CLICKS                                 AS INLINE_LINK_CLICK_QTY
,INLINE_LINK_CLICK_CTR                              AS INLINE_LINK_CLICK_THROUGH_PCT
,INLINE_POST_ENGAGEMENT                             AS INLINE_POST_ENGAGEMENT_QTY
,COST_PER_INLINE_LINK_CLICK                         AS PER_INLINE_LINK_CLICK_COST_AMT
,COST_PER_INLINE_POST_ENGAGEMENT                    AS PER_INLINE_POST_ENGAGEMENT_COST_AMT
,COST_PER_UNIQUE_CLICK                              AS PER_UNIQUE_CLICK_COST_AMT
,COST_PER_UNIQUE_INLINE_LINK_CLICK                  AS PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT
,OBJECTIVE                                          AS OBJECTIVE_DC
,REACH                                              AS REACH_QTY
,SPEND                                              AS SPEND_QTY
,UNIQUE_CLICKS                                      AS UNIQUE_CLICK_QTY
,UNIQUE_CTR                                         AS UNIQUE_CLICK_THROUGH_PCT
,UNIQUE_INLINE_LINK_CLICKS                          AS UNIQUE_INLINE_LINK_CLICK_QTY
,UNIQUE_INLINE_LINK_CLICK_CTR                       AS UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT
,UNIQUE_LINK_CLICKS_CTR                             AS UNIQUE_LINK_CLICK_THROUGH_PCT
FROM FACEBOOK_ADS.ADS_INSIGHTS_REGION
)

SELECT
 C.CD2_AD_ID                                        AS CD2_AD_ID
,D.CD2_ADSET_ID                                     AS CD2_ADSET_ID
,E.CD2_CAMPAIGN_ID                                  AS CD2_CAMPAIGN_ID
,A.REGION_DC                                        AS REGION_DC
,CURRENT_DATE || ' ' || CURRENT_TIME                AS LOAD_DTTM
,A.START_DTTM::DATETIME                             AS START_DTTM
,A.STOP_DTTM::DATETIME                              AS STOP_DTTM
,A.ACTION_ARRAY                                     AS ACTION_ARRAY
,A.OUTBOUND_CLICK_ARRAY                             AS OUTBOUND_CLICK_ARRAY
,A.UNIQUE_ACTION_ARRAY                              AS UNIQUE_ACTION_ARRAY
,A.UNIQUE_OUTBOUND_CLICK_ARRAY                      AS UNIQUE_OUTBOUND_CLICK_ARRAY
,A.WEBSITE_CLICK_THROUGH_ARRAY                      AS WEBSITE_CLICK_THROUGH_ARRAY
,IFNULL(A.CLICK_QTY, 0)                             AS CLICK_QTY
,IFNULL(A.PER_INLINE_LINK_CLICK_COST_AMT, 0)        AS PER_INLINE_LINK_CLICK_COST_AMT
,IFNULL(A.PER_INLINE_POST_ENGAGEMENT_COST_AMT, 0)   AS PER_INLINE_POST_ENGAGEMENT_COST_AMT
,IFNULL(A.PER_UNIQUE_CLICK_COST_AMT, 0)             AS PER_UNIQUE_CLICK_COST_AMT
,IFNULL(A.PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT, 0) AS PER_UNIQUE_INLINE_LINK_CLICK_COST_AMT
,IFNULL(A.AVERAGE_CPC_COST_AMT, 0)                  AS AVERAGE_CPC_COST_AMT
,IFNULL(A.AVERAGE_CPM_COST_AMT, 0)                  AS AVERAGE_CPM_COST_AMT
,IFNULL(A.PER_POINT_COST_AMT, 0)                    AS PER_POINT_COST_AMT
,IFNULL(A.CLICK_THROUGH_RATE_AMT, 0)                AS CLICK_THROUGH_RATE_AMT
,IFNULL(A.FREQUENCY_QTY, 0)                         AS FREQUENCY_QTY
,IFNULL(A.IMPRESSIONS_QTY, 0)                       AS IMPRESSIONS_QTY
,IFNULL(A.INLINE_LINK_CLICK_QTY, 0)                 AS INLINE_LINK_CLICK_QTY
,IFNULL(A.INLINE_LINK_CLICK_THROUGH_PCT, 0)         AS INLINE_LINK_CLICK_THROUGH_PCT
,IFNULL(A.INLINE_POST_ENGAGEMENT_QTY, 0)            AS INLINE_POST_ENGAGEMENT_QTY
,A.OBJECTIVE_DC                                     AS OBJECTIVE_DC
,IFNULL(A.REACH_QTY, 0)                             AS REACH_QTY
,IFNULL(A.SPEND_QTY, 0)                             AS SEND_QTY
,IFNULL(A.UNIQUE_CLICK_QTY, 0)                      AS UNIQUE_CLICK_QTY
,IFNULL(A.UNIQUE_CLICK_THROUGH_PCT, 0)              AS UNIQUE_CLICK_THROUGH_PCT
,IFNULL(A.UNIQUE_INLINE_LINK_CLICK_QTY, 0)          AS UNIQUE_INLINE_LINK_CLICK_QTY
,IFNULL(A.UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT, 0)  AS UNIQUE_INLINE_LINK_CLICK_THROUGH_PCT
,IFNULL(A.UNIQUE_LINK_CLICK_THROUGH_PCT, 0)         AS UNIQUE_LINK_CLICK_THROUGH_PCT
FROM SRC_ADS_REGION            AS A
JOIN DM_ADS.CD2_AD             AS C ON     A.AD_ID          = C.AD_ID
                                       AND C.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_ADSET          AS D ON     A.ADSET_ID       = D.ADSET_ID
                                       AND D.CURR_REC_IND   = 'Y'
JOIN DM_ADS.CD2_CAMPAIGN       AS E ON     A.CAMPAIGN_ID    = E.CAMPAIGN_ID
                                       AND E.CURR_REC_IND   = 'Y';

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.GOOGLE_ADS.VW_FS_GOOGLE_ADS_PERFORMANCE_ACCOUNT AS

WITH SRC_ADS_ACCOUNT AS
(SELECT
 TO_TIMESTAMP_NTZ(LEFT("DATE",LEN("DATE") -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS LOAD_DTTM
,AD_NETWORK_TYPE                        AS AD_NETWORK_TYPE_DC
,CUSTOMER_ID                            AS CUSTOMER_ID
,DEVICE                                 AS DEVICE_DC
,ACTIVE_VIEW_CPM                        AS ACTIVE_VIEW_COST_PER_MILE_AMT
,ACTIVE_VIEW_CTR                        AS ACTIVE_VIEW_CLICK_THROUGH_PCT
,ACTIVE_VIEW_IMPRESSIONS                AS ACTIVE_VIEW_IMPRESSIONS_QTY
,ACTIVE_VIEW_MEASURABILITY              AS ACTIVE_VIEW_MEASURABILITY_PCT
,ACTIVE_VIEW_MEASURABLE_COST_MICROS     AS ACTIVE_VIEW_MEASURABLE_COST_MICROS_QTY
,ACTIVE_VIEW_MEASURABLE_IMPRESSIONS     AS ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_QTY
,ACTIVE_VIEW_VIEWABILITY                AS ACTIVE_VIEW_VIEWABILITY_PCT
,ALL_CONVERSIONS                        AS ALL_CONVERSIONS_PCT
,ALL_CONVERSIONS_FROM_INTERACTIONS_RATE AS ALL_CONVERSIONS_FROM_INTERACTIONS_PCT
,ALL_CONVERSIONS_VALUE                  AS ALL_CONVERSIONS_VALUE_AMT
,AVERAGE_COST                           AS AVERAGE_COST_AMT
,AVERAGE_CPC                            AS AVERAGE_COST_PER_CLICK_AMT
,AVERAGE_CPM                            AS AVERAGE_COST_PER_MILE_AMT
,CLICKS                                 AS CLICKS_QTY
,CONTENT_BUDGET_LOST_IMPRESSION_SHARE   AS CONTENT_BUDGET_LOST_IMPRESSION_SHARE_PCT
,CONTENT_IMPRESSION_SHARE               AS CONTENT_IMPRESSION_SHARE_PCT
,CONTENT_RANK_LOST_IMPRESSION_SHARE     AS CONTENT_RANK_LOST_IMPRESSION_SHARE_PCT
,CONVERSIONS                            AS CONVERSIONS_PCT
,CONVERSIONS_FROM_INTERACTIONS_RATE     AS CONVERSIONS_FROM_INTERACTIONS_PCT
,CONVERSIONS_VALUE                      AS CONVERSIONS_VALUE_PCT
,COST_MICROS                            AS COST_MICROS_QTY
,CROSS_DEVICE_CONVERSIONS               AS CROSS_DEVICE_CONVERSIONS_PCT
,CTR                                    AS CLICK_THROUGH_PCT
,CASE
 WHEN CUSTOMER_AUTO_TAGGING_ENABLED = 0 THEN 'N'
 ELSE 'Y'
 END                                    AS CUSTOMER_AUTO_TAGGING_ENABLED_IND
,CUSTOMER_CURRENCY_CODE                 AS CUSTOMER_CURRENCY_CD
,CASE
 WHEN CUSTOMER_MANAGER = 0 THEN 'N'
 ELSE 'Y'
 END                                    AS CUSTOMER_MANAGER_IND
,CASE
 WHEN CUSTOMER_TEST_ACCOUNT = 0 THEN 'N'
 ELSE 'Y'
 END                                    AS CUSTOMER_TEST_ACCOUNT_IND
,CUSTOMER_TIME_ZONE                     AS CUSTOMER_TIME_ZONE_DC
,ENGAGEMENTS                            AS ENGAGEMENTS_QTY
,IMPRESSIONS                            AS IMPRESSIONS_QTY
,INTERACTIONS                           AS INTERACTIONS_QTY
,INTERACTION_EVENT_TYPES                AS INTERACTION_EVENT_TYPES_DC
,INTERACTION_RATE                       AS INTERACTION_PCT
,INVALID_CLICKS                         AS INVALID_CLICKS_QTY
,INVALID_CLICK_RATE                     AS INVALID_CLICK_PCT
,VIDEO_VIEWS                            AS VIDEO_VIEWS_QTY
,VIEW_THROUGH_CONVERSIONS               AS VIEW_THROUGH_CONVERSIONS_QTY
FROM GOOGLE_ADS.ACCOUNT_PERFORMANCE_REPORT
)

SELECT
 LOAD_DTTM
,AD_NETWORK_TYPE_DC
,CUSTOMER_ID
,DEVICE_DC
,ACTIVE_VIEW_COST_PER_MILE_AMT
,ACTIVE_VIEW_CLICK_THROUGH_PCT
,ACTIVE_VIEW_IMPRESSIONS_QTY
,ACTIVE_VIEW_MEASURABILITY_PCT
,ACTIVE_VIEW_MEASURABLE_COST_MICROS_QTY
,ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_QTY
,ACTIVE_VIEW_VIEWABILITY_PCT
,ALL_CONVERSIONS_PCT
,ALL_CONVERSIONS_FROM_INTERACTIONS_PCT
,ALL_CONVERSIONS_VALUE_AMT
,AVERAGE_COST_AMT
,AVERAGE_COST_PER_CLICK_AMT
,AVERAGE_COST_PER_MILE_AMT
,CLICKS_QTY
,CONTENT_BUDGET_LOST_IMPRESSION_SHARE_PCT
,CONTENT_IMPRESSION_SHARE_PCT
,CONTENT_RANK_LOST_IMPRESSION_SHARE_PCT
,CONVERSIONS_PCT
,CONVERSIONS_FROM_INTERACTIONS_PCT
,CONVERSIONS_VALUE_PCT
,COST_MICROS_QTY
,CROSS_DEVICE_CONVERSIONS_PCT
,CLICK_THROUGH_PCT
,CUSTOMER_AUTO_TAGGING_ENABLED_IND
,CUSTOMER_CURRENCY_CD
,CUSTOMER_MANAGER_IND
,CUSTOMER_TEST_ACCOUNT_IND
,CUSTOMER_TIME_ZONE_DC
,ENGAGEMENTS_QTY
,IMPRESSIONS_QTY
,INTERACTIONS_QTY
,INTERACTION_EVENT_TYPES_DC
,INTERACTION_PCT
,INVALID_CLICKS_QTY
,INVALID_CLICK_PCT
,VIDEO_VIEWS_QTY
,VIEW_THROUGH_CONVERSIONS_QTY
FROM SRC_ADS_ACCOUNT;

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.GOOGLE_ADS.VW_FS_GOOGLE_ADS_PERFORMANCE_CAMPAIGN AS

WITH SRC_ADS_CAMPAIGN AS
(SELECT
 TO_TIMESTAMP_NTZ(LEFT("DATE",LEN("DATE") -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS LOAD_DTTM
,AD_NETWORK_TYPE                                 AS AD_NETWORK_TYPE_DC
,CUSTOMER_ID                                     AS CUSTOMER_ID
,CAMPAIGN_ID                                     AS CAMPAIGN_ID
,ABSOLUTE_TOP_IMPRESSION_PERCENTAGE              AS ABSOLUTE_TOP_IMPRESSION_PCT
,ACTIVE_VIEW_CPM                                 AS ACTIVE_VIEW_COST_PER_MILE_AMT
,ACTIVE_VIEW_CTR                                 AS ACTIVE_VIEW_CLICK_THROUGH_PCT
,ACTIVE_VIEW_IMPRESSIONS                         AS ACTIVE_VIEW_IMPRESSIONS_QTY
,ACTIVE_VIEW_MEASURABILITY                       AS ACTIVE_VIEW_MEASURABILITY_PCT
,ACTIVE_VIEW_MEASURABLE_COST_MICROS              AS ACTIVE_VIEW_MEASURABLE_COST_MICROS_QTY
,ACTIVE_VIEW_MEASURABLE_IMPRESSIONS              AS ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_QTY
,ACTIVE_VIEW_VIEWABILITY                         AS ACTIVE_VIEW_VIEWABILITY_PCT
,ALL_CONVERSIONS                                 AS ALL_CONVERSIONS_PCT
,ALL_CONVERSIONS_FROM_INTERACTIONS_RATE          AS ALL_CONVERSIONS_FROM_INTERACTIONS_PCT
,ALL_CONVERSIONS_VALUE                           AS ALL_CONVERSIONS_VALUE_PCT
,AVERAGE_COST                                    AS AVERAGE_COST_AMT
,AVERAGE_CPC                                     AS AVERAGE_COST_PER_CLICK_AMT
,AVERAGE_CPM                                     AS AVERAGE_COST_PER_THOUSAND_IMPRESSIONS_AMT
,BIDDING_STRATEGY_NAME                           AS BIDDING_STRATEGY_NM
,CAMPAIGN_ADVERTISING_CHANNEL_SUB_TYPE           AS CAMPAIGN_ADVERTISING_CHANNEL_SUB_TYPE_DC
,CAMPAIGN_ADVERTISING_CHANNEL_TYPE               AS CAMPAIGN_ADVERTISING_CHANNEL_TYPE_DC
,CAMPAIGN_BASE_CAMPAIGN                          AS CAMPAIGN_BASE_CAMPAIGN_DC
,CAMPAIGN_BIDDING_STRATEGY                       AS CAMPAIGN_BIDDING_STRATEGY_DC
,CAMPAIGN_BIDDING_STRATEGY_TYPE                  AS CAMPAIGN_BIDDING_STRATEGY_TYPE_DC
,CAMPAIGN_BUDGET_AMOUNT_MICROS                   AS CAMPAIGN_BUDGET_AMOUNT_MICROS_QTY
,CASE
 WHEN CAMPAIGN_BUDGET_EXPLICITLY_SHARED = 0 THEN 'N'
 ELSE 'Y'
 END                                             AS CAMPAIGN_BUDGET_EXPLICITLY_SHARED_IND
,CASE
 WHEN CAMPAIGN_BUDGET_HAS_RECOMMENDED_BUDGET = 0 THEN 'N'
 ELSE 'Y'
 END                                             AS CAMPAIGN_BUDGET_HAS_RECOMMENDED_BUDGET_IND
,CAMPAIGN_BUDGET_PERIOD                          AS CAMPAIGN_BUDGET_PERIOD_DC
,CAMPAIGN_CAMPAIGN_BUDGET                        AS CAMPAIGN_CAMPAIGN_BUDGET_DC
,TO_TIMESTAMP_NTZ(LEFT(CAMPAIGN_END_DATE,LEN(CAMPAIGN_END_DATE) -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS CAMPAIGN_END_DTTM
,CAMPAIGN_EXPERIMENT_TYPE                        AS CAMPAIGN_EXPERIMENT_TYPE_DC
,CAMPAIGN_NAME                                   AS CAMPAIGN_NM
,CAMPAIGN_SERVING_STATUS                         AS CAMPAIGN_SERVING_STATUS_DC
,TO_TIMESTAMP_NTZ(LEFT(CAMPAIGN_START_DATE,LEN(CAMPAIGN_START_DATE) -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS CAMPAIGN_START_DTTM
,CAMPAIGN_STATUS                                 AS CAMPAIGN_STATUS_DC
,CLICKS                                          AS CLICKS_QTY
,CONTENT_BUDGET_LOST_IMPRESSION_SHARE            AS CONTENT_BUDGET_LOST_IMPRESSION_SHARE_PCT
,CONTENT_IMPRESSION_SHARE                        AS CONTENT_IMPRESSION_SHARE_PCT
,CONTENT_RANK_LOST_IMPRESSION_SHARE              AS CONTENT_RANK_LOST_IMPRESSION_SHARE_PCT
,CONVERSIONS                                     AS CONVERSIONS_PCT
,CONVERSIONS_FROM_INTERACTIONS_RATE              AS CONVERSIONS_FROM_INTERACTIONS_PCT
,CONVERSIONS_VALUE                               AS CONVERSIONS_VALUE_AMT
,COST_MICROS                                     AS COST_MICROS_QTY
,CROSS_DEVICE_CONVERSIONS                        AS CROSS_DEVICE_CONVERSIONS_PCT
,CTR                                             AS CLICK_THROUGH_PCT
,CURRENT_MODEL_ATTRIBUTED_CONVERSIONS            AS CURRENT_MODEL_ATTRIBUTED_CONVERSIONS_PCT
,CURRENT_MODEL_ATTRIBUTED_CONVERSIONS_VALUE      AS CURRENT_MODEL_ATTRIBUTED_CONVERSIONS_VALUE_PCT
,CUSTOMER_CURRENCY_CODE                          AS CUSTOMER_CURRENCY_CD
,CUSTOMER_TIME_ZONE                              AS CUSTOMER_TIME_ZONE_DC
,ENGAGEMENTS                                     AS ENGAGEMENTS_QTY
,GMAIL_FORWARDS                                  AS GMAIL_FORWARDS_QTY
,GMAIL_SAVES                                     AS GMAIL_SAVES_QTY
,GMAIL_SECONDARY_CLICKS                          AS GMAIL_SECONDARY_CLICKS_QTY
,IMPRESSIONS                                     AS IMPRESSIONS_QTY
,INTERACTIONS                                    AS INTERACTIONS_QTY
,INTERACTION_EVENT_TYPES                         AS INTERACTION_EVENT_TYPES_DC
,INTERACTION_RATE                                AS INTERACTION_PCT
,INVALID_CLICKS                                  AS INVALID_CLICKS_QTY
,INVALID_CLICK_RATE                              AS INVALID_CLICK_PCT
,PHONE_CALLS                                     AS PHONE_CALLS_QTY
,PHONE_IMPRESSIONS                               AS PHONE_IMPRESSIONS_QTY
,PHONE_THROUGH_RATE                              AS PHONE_THROUGH_PCT
,SEARCH_CLICK_SHARE                              AS SEARCH_CLICK_SHARE_PCT
,TOP_IMPRESSION_PERCENTAGE                       AS TOP_IMPRESSION_PCT
,VIDEO_QUARTILE_P25_RATE                         AS VIDEO_QUARTILE_P025_PCT
,VIDEO_QUARTILE_P50_RATE                         AS VIDEO_QUARTILE_P050_PCT
,VIDEO_QUARTILE_P75_RATE                         AS VIDEO_QUARTILE_P075_PCT
,VIDEO_QUARTILE_P100_RATE                        AS VIDEO_QUARTILE_P100_PCT
,VIDEO_VIEWS                                     AS VIDEO_VIEWS_QTY
,VIEW_THROUGH_CONVERSIONS                        AS VIEW_THROUGH_CONVERSIONS_QTY
FROM GOOGLE_ADS.CAMPAIGN_PERFORMANCE_REPORT
)

SELECT
 LOAD_DTTM
,AD_NETWORK_TYPE_DC
,CUSTOMER_ID
,CAMPAIGN_ID
,ABSOLUTE_TOP_IMPRESSION_PCT
,ACTIVE_VIEW_COST_PER_MILE_AMT
,ACTIVE_VIEW_CLICK_THROUGH_PCT
,ACTIVE_VIEW_IMPRESSIONS_QTY
,ACTIVE_VIEW_MEASURABILITY_PCT
,ACTIVE_VIEW_MEASURABLE_COST_MICROS_QTY
,ACTIVE_VIEW_MEASURABLE_IMPRESSIONS_QTY
,ACTIVE_VIEW_VIEWABILITY_PCT
,ALL_CONVERSIONS_PCT
,ALL_CONVERSIONS_FROM_INTERACTIONS_PCT
,ALL_CONVERSIONS_VALUE_PCT
,AVERAGE_COST_AMT
,AVERAGE_COST_PER_CLICK_AMT
,AVERAGE_COST_PER_THOUSAND_IMPRESSIONS_AMT
,BIDDING_STRATEGY_NM
,CAMPAIGN_ADVERTISING_CHANNEL_SUB_TYPE_DC
,CAMPAIGN_ADVERTISING_CHANNEL_TYPE_DC
,CAMPAIGN_BASE_CAMPAIGN_DC
,CAMPAIGN_BIDDING_STRATEGY_DC
,CAMPAIGN_BIDDING_STRATEGY_TYPE_DC
,CAMPAIGN_BUDGET_AMOUNT_MICROS_QTY
,CAMPAIGN_BUDGET_EXPLICITLY_SHARED_IND
,CAMPAIGN_BUDGET_HAS_RECOMMENDED_BUDGET_IND
,CAMPAIGN_BUDGET_PERIOD_DC
,CAMPAIGN_CAMPAIGN_BUDGET_DC
,CAMPAIGN_END_DTTM
,CAMPAIGN_EXPERIMENT_TYPE_DC
,CAMPAIGN_NM
,CAMPAIGN_SERVING_STATUS_DC
,CAMPAIGN_START_DTTM
,CAMPAIGN_STATUS_DC
,CLICKS_QTY
,CONTENT_BUDGET_LOST_IMPRESSION_SHARE_PCT
,CONTENT_IMPRESSION_SHARE_PCT
,CONTENT_RANK_LOST_IMPRESSION_SHARE_PCT
,CONVERSIONS_PCT
,CONVERSIONS_FROM_INTERACTIONS_PCT
,CONVERSIONS_VALUE_AMT
,COST_MICROS_QTY
,CROSS_DEVICE_CONVERSIONS_PCT
,CLICK_THROUGH_PCT
,CURRENT_MODEL_ATTRIBUTED_CONVERSIONS_PCT
,CURRENT_MODEL_ATTRIBUTED_CONVERSIONS_VALUE_PCT
,CUSTOMER_CURRENCY_CD
,CUSTOMER_TIME_ZONE_DC
,ENGAGEMENTS_QTY
,GMAIL_FORWARDS_QTY
,GMAIL_SAVES_QTY
,GMAIL_SECONDARY_CLICKS_QTY
,IMPRESSIONS_QTY
,INTERACTIONS_QTY
,INTERACTION_EVENT_TYPES_DC
,INTERACTION_PCT
,INVALID_CLICKS_QTY
,INVALID_CLICK_PCT
,PHONE_CALLS_QTY
,PHONE_IMPRESSIONS_QTY
,PHONE_THROUGH_PCT
,SEARCH_CLICK_SHARE_PCT
,TOP_IMPRESSION_PCT
,VIDEO_QUARTILE_P025_PCT
,VIDEO_QUARTILE_P050_PCT
,VIDEO_QUARTILE_P075_PCT
,VIDEO_QUARTILE_P100_PCT
,VIDEO_VIEWS_QTY
,VIEW_THROUGH_CONVERSIONS_QTY
FROM SRC_ADS_CAMPAIGN;

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.GOOGLE_ADS.VW_FS_GOOGLE_ADS_PERFORMANCE_CLICK AS

WITH SRC_ADS_CAMPAIGN AS
(SELECT
  TO_TIMESTAMP_NTZ(LEFT("DATE",LEN("DATE") -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS LOAD_DTTM
 ,AD_GROUP_ID                                                               AS AD_GROUP_ID
 ,AD_NETWORK_TYPE                                                           AS AD_NETWORK_TYPE_DC
 ,DEVICE                                                                    AS DEVICE_DC
 ,CAMPAIGN_ID                                                               AS CAMPAIGN_ID
 ,CAMPAIGN_NAME                                                             AS CAMPAIGN_NM
 ,CLICK_VIEW_GCLID                                                          AS CLICK_VIEW_GCL_ID
 ,CUSTOMER_ID                                                               AS CUSTOMER_ID
 ,CLICK_VIEW_LOCATION_OF_PRESENCE::VARCHAR(200000)                          AS CLICK_VIEW_LOCATION_OF_PRESENCE_ARRAY
 ,CAMPAIGN_STATUS                                                           AS CAMPAIGN_STATUS_DC
 ,CLICKS                                                                    AS CLICKS_QTY
 ,CLICK_TYPE                                                                AS CLICK_TYPE_DC
 ,CLICK_VIEW_AD_GROUP_AD                                                    AS CLICK_VIEW_AD_GROUP_AD_DC
 ,CLICK_VIEW_CAMPAIGN_LOCATION_TARGET                                       AS CLICK_VIEW_CAMPAIGN_LOCATION_TARGET_DC
 ,CLICK_VIEW_PAGE_NUMBER                                                    AS CLICK_VIEW_PAGE_NR
 ,SLOT                                                                      AS SLOT_DC
 FROM GOOGLE_ADS.CLICK_PERFORMANCE_REPORT
)

SELECT
 LOAD_DTTM
,AD_GROUP_ID
,AD_NETWORK_TYPE_DC
,DEVICE_DC
,CAMPAIGN_ID
,CAMPAIGN_NM
,CLICK_VIEW_GCL_ID
,CUSTOMER_ID
,CLICK_VIEW_LOCATION_OF_PRESENCE_ARRAY
,CAMPAIGN_STATUS_DC
,CLICKS_QTY
,CLICK_TYPE_DC
,CLICK_VIEW_AD_GROUP_AD_DC
,CLICK_VIEW_CAMPAIGN_LOCATION_TARGET_DC
,CLICK_VIEW_PAGE_NR
,SLOT_DC
FROM SRC_ADS_CAMPAIGN;

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.LINKEDIN.VW_LINKEDIN_FS_ADS_ANALYTICS_BY_CAMPAIGN AS

WITH SRC_ADS_CAMPAIGN AS
(SELECT
  CAMPAIGN_ID                                               AS CAMPAIGN_ID
 ,CAMPAIGN                                                  AS CAMPAIGN_DC
 ,TO_TIMESTAMP_NTZ(LEFT(START_AT,LEN(START_AT) -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS START_AT_DTTM
 ,TO_TIMESTAMP_NTZ(LEFT(  END_AT,LEN(END_AT  ) -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS END_AT_DTTM
 ,DATE_RANGE::VARCHAR(200000)                               AS DATE_RANGE_ARRAY
 ,PIVOT_VALUES::VARCHAR(200000)                             AS PIVOT_VALUES_ARRAY
 ,PIVOT                                                     AS PIVOT_DC
 ,PIVOT_VALUE                                               AS PIVOT_VALUE_DC
 ,ACTION_CLICKS                                             AS ACTION_CLICKS_QTY
 ,AD_UNIT_CLICKS                                            AS AD_UNIT_CLICKS_QTY
 ,APPROXIMATE_UNIQUE_IMPRESSIONS                            AS APPROXIMATE_UNIQUE_IMPRESSIONS_QTY
 ,CARD_CLICKS                                               AS CARD_CLICKS_QTY
 ,CARD_IMPRESSIONS                                          AS CARD_IMPRESSIONS_QTY
 ,CLICKS                                                    AS CLICKS_QTY
 ,COMMENTS                                                  AS COMMENTS_QTY
 ,COMMENT_LIKES                                             AS COMMENT_LIKES_QTY
 ,COMPANY_PAGE_CLICKS                                       AS COMPANY_PAGE_CLICKS_QTY
 ,CONVERSION_VALUE_IN_LOCAL_CURRENCY                        AS CONVERSION_VALUE_IN_LOCAL_CURRENCY_AMT
 ,COST_IN_LOCAL_CURRENCY                                    AS COST_IN_LOCAL_CURRENCY_AMT
 ,COST_IN_USD                                               AS COST_IN_USD_AMT
 ,DOCUMENT_COMPLETIONS                                      AS DOCUMENT_COMPLETIONS_QTY
 ,DOCUMENT_FIRST_QUARTILE_COMPLETIONS                       AS DOCUMENT_FIRST_QUARTILE_COMPLETIONS_QTY
 ,DOCUMENT_MIDPOINT_COMPLETIONS                             AS DOCUMENT_MIDPOINT_COMPLETIONS_QTY
 ,DOCUMENT_THIRD_QUARTILE_COMPLETIONS                       AS DOCUMENT_THIRD_QUARTILE_COMPLETIONS_QTY
 ,DOWNLOAD_CLICKS                                           AS DOWNLOAD_CLICKS_QTY
 ,EXTERNAL_WEBSITE_CONVERSIONS                              AS EXTERNAL_WEBSITE_CONVERSIONS_QTY
 ,EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS                   AS EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS_QTY
 ,EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS                    AS EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS_QTY
 ,FOLLOWS                                                   AS FOLLOWS_QTY
 ,FULL_SCREEN_PLAYS                                         AS FULL_SCREEN_PLAYS_QTY
 ,IMPRESSIONS                                               AS IMPRESSIONS_QTY
 ,JOB_APPLICATIONS                                          AS JOB_APPLICATIONS_QTY
 ,JOB_APPLY_CLICKS                                          AS JOB_APPLY_CLICKS_QTY
 ,LANDING_PAGE_CLICKS                                       AS LANDING_PAGE_CLICKS_QTY
 ,LEAD_GENERATION_MAIL_CONTACT_INFO_SHARES                  AS LEAD_GENERATION_MAIL_CONTACT_INFO_SHARES_QTY
 ,LEAD_GENERATION_MAIL_INTERESTED_CLICKS                    AS LEAD_GENERATION_MAIL_INTERESTED_CLICKS_QTY
 ,LIKES                                                     AS LIKES_QTY
 ,ONE_CLICK_LEADS                                           AS ONE_CLICK_LEADS_QTY
 ,ONE_CLICK_LEAD_FORM_OPENS                                 AS ONE_CLICK_LEAD_FORM_OPENS_QTY
 ,OPENS                                                     AS OPENS_QTY
 ,OTHER_ENGAGEMENTS                                         AS OTHER_ENGAGEMENTS_QTY
 ,POST_CLICK_JOB_APPLICATIONS                               AS POST_CLICK_JOB_APPLICATIONS_QTY
 ,POST_CLICK_JOB_APPLY_CLICKS                               AS POST_CLICK_JOB_APPLY_CLICKS_QTY
 ,POST_CLICK_REGISTRATIONS                                  AS POST_CLICK_REGISTRATIONS_QTY
 ,POST_VIEW_JOB_APPLICATIONS                                AS POST_VIEW_JOB_APPLICATIONS_QTY
 ,POST_VIEW_JOB_APPLY_CLICKS                                AS POST_VIEW_JOB_APPLY_CLICKS_QTY
 ,POST_VIEW_REGISTRATIONS                                   AS POST_VIEW_REGISTRATIONS_QTY
 ,REACTIONS                                                 AS REACTIONS_QTY
 ,REGISTRATIONS                                             AS REGISTRATIONS_QTY
 ,SENDS                                                     AS SENDS_QTY
 ,SHARES                                                    AS SHARES_QTY
 ,TALENT_LEADS                                              AS TALENT_LEADS_QTY
 ,TEXT_URL_CLICKS                                           AS TEXT_URL_CLICKS_QTY
 ,TOTAL_ENGAGEMENTS                                         AS TOTAL_ENGAGEMENTS_QTY
 ,VIDEO_COMPLETIONS                                         AS VIDEO_COMPLETIONS_QTY
 ,VIDEO_FIRST_QUARTILE_COMPLETIONS                          AS VIDEO_FIRST_QUARTILE_COMPLETIONS_QTY
 ,VIDEO_MIDPOINT_COMPLETIONS                                AS VIDEO_MIDPOINT_COMPLETIONS_QTY
 ,VIDEO_STARTS                                              AS VIDEO_STARTS_QTY
 ,VIDEO_THIRD_QUARTILE_COMPLETIONS                          AS VIDEO_THIRD_QUARTILE_COMPLETIONS_QTY
 ,VIDEO_VIEWS                                               AS VIDEO_VIEWS_QTY
 ,VIRAL_CARD_CLICKS                                         AS VIRAL_CARD_CLICKS_QTY
 ,VIRAL_CARD_IMPRESSIONS                                    AS VIRAL_CARD_IMPRESSIONS_QTY
 ,VIRAL_CLICKS                                              AS VIRAL_CLICKS_QTY
 ,VIRAL_COMMENTS                                            AS VIRAL_COMMENTS_QTY
 ,VIRAL_COMMENT_LIKES                                       AS VIRAL_COMMENT_LIKES_QTY
 ,VIRAL_COMPANY_PAGE_CLICKS                                 AS VIRAL_COMPANY_PAGE_CLICKS_QTY
 ,VIRAL_DOCUMENT_COMPLETIONS                                AS VIRAL_DOCUMENT_COMPLETIONS_QTY
 ,VIRAL_DOCUMENT_FIRST_QUARTILE_COMPLETIONS                 AS VIRAL_DOCUMENT_FIRST_QUARTILE_COMPLETIONS_QTY
 ,VIRAL_DOCUMENT_MIDPOINT_COMPLETIONS                       AS VIRAL_DOCUMENT_MIDPOINT_COMPLETIONS_QTY
 ,VIRAL_DOCUMENT_THIRD_QUARTILE_COMPLETIONS                 AS VIRAL_DOCUMENT_THIRD_QUARTILE_COMPLETIONS_QTY
 ,VIRAL_DOWNLOAD_CLICKS                                     AS VIRAL_DOWNLOAD_CLICKS_QTY
 ,VIRAL_EXTERNAL_WEBSITE_CONVERSIONS                        AS VIRAL_EXTERNAL_WEBSITE_CONVERSIONS_QTY
 ,VIRAL_EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS             AS VIRAL_EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS_QTY
 ,VIRAL_EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS              AS VIRAL_EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS_QTY
 ,VIRAL_FOLLOWS                                             AS VIRAL_FOLLOWS_QTY
 ,VIRAL_FULL_SCREEN_PLAYS                                   AS VIRAL_FULL_SCREEN_PLAYS_QTY
 ,VIRAL_IMPRESSIONS                                         AS VIRAL_IMPRESSIONS_QTY
 ,VIRAL_JOB_APPLICATIONS                                    AS VIRAL_JOB_APPLICATIONS_QTY
 ,VIRAL_JOB_APPLY_CLICKS                                    AS VIRAL_JOB_APPLY_CLICKS_QTY
 ,VIRAL_LANDING_PAGE_CLICKS                                 AS VIRAL_LANDING_PAGE_CLICKS_QTY
 ,VIRAL_LIKES                                               AS VIRAL_LIKES_QTY
 ,VIRAL_ONE_CLICK_LEADS                                     AS VIRAL_ONE_CLICK_LEADS_QTY
 ,VIRAL_ONE_CLICK_LEAD_FORM_OPENS                           AS VIRAL_ONE_CLICK_LEAD_FORM_OPENS_QTY
 ,VIRAL_OTHER_ENGAGEMENTS                                   AS VIRAL_OTHER_ENGAGEMENTS_QTY
 ,VIRAL_POST_CLICK_JOB_APPLICATIONS                         AS VIRAL_POST_CLICK_JOB_APPLICATIONS_QTY
 ,VIRAL_POST_CLICK_JOB_APPLY_CLICKS                         AS VIRAL_POST_CLICK_JOB_APPLY_CLICKS_QTY
 ,VIRAL_POST_CLICK_REGISTRATIONS                            AS VIRAL_POST_CLICK_REGISTRATIONS_QTY
 ,VIRAL_POST_VIEW_JOB_APPLICATIONS                          AS VIRAL_POST_VIEW_JOB_APPLICATIONS_QTY
 ,VIRAL_POST_VIEW_JOB_APPLY_CLICKS                          AS VIRAL_POST_VIEW_JOB_APPLY_CLICKS_QTY
 ,VIRAL_POST_VIEW_REGISTRATIONS                             AS VIRAL_POST_VIEW_REGISTRATIONS_QTY
 ,VIRAL_REACTIONS                                           AS VIRAL_REACTIONS_QTY
 ,VIRAL_REGISTRATIONS                                       AS VIRAL_REGISTRATIONS_QTY
 ,VIRAL_SHARES                                              AS VIRAL_SHARES_QTY
 ,VIRAL_TOTAL_ENGAGEMENTS                                   AS VIRAL_TOTAL_ENGAGEMENTS_QTY
 ,VIRAL_VIDEO_COMPLETIONS                                   AS VIRAL_VIDEO_COMPLETIONS_QTY
 ,VIRAL_VIDEO_FIRST_QUARTILE_COMPLETIONS                    AS VIRAL_VIDEO_FIRST_QUARTILE_COMPLETIONS_QTY
 ,VIRAL_VIDEO_MIDPOINT_COMPLETIONS                          AS VIRAL_VIDEO_MIDPOINT_COMPLETIONS_QTY
 ,VIRAL_VIDEO_STARTS                                        AS VIRAL_VIDEO_STARTS_QTY
 ,VIRAL_VIDEO_THIRD_QUARTILE_COMPLETIONS                    AS VIRAL_VIDEO_THIRD_QUARTILE_COMPLETIONS_QTY
 ,VIRAL_VIDEO_VIEWS                                         AS VIRAL_VIDEO_VIEWS_QTY
FROM LINKEDIN.AD_ANALYTICS_BY_CAMPAIGN
)

SELECT
 CAMPAIGN_ID
,CAMPAIGN_DC
,START_AT_DTTM
,END_AT_DTTM
,DATE_RANGE_ARRAY
,PIVOT_VALUES_ARRAY
,PIVOT_DC
,PIVOT_VALUE_DC
,ACTION_CLICKS_QTY
,AD_UNIT_CLICKS_QTY
,APPROXIMATE_UNIQUE_IMPRESSIONS_QTY
,CARD_CLICKS_QTY
,CARD_IMPRESSIONS_QTY
,CLICKS_QTY
,COMMENTS_QTY
,COMMENT_LIKES_QTY
,COMPANY_PAGE_CLICKS_QTY
,CONVERSION_VALUE_IN_LOCAL_CURRENCY_AMT
,COST_IN_LOCAL_CURRENCY_AMT
,COST_IN_USD_AMT
,DOCUMENT_COMPLETIONS_QTY
,DOCUMENT_FIRST_QUARTILE_COMPLETIONS_QTY
,DOCUMENT_MIDPOINT_COMPLETIONS_QTY
,DOCUMENT_THIRD_QUARTILE_COMPLETIONS_QTY
,DOWNLOAD_CLICKS_QTY
,EXTERNAL_WEBSITE_CONVERSIONS_QTY
,EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS_QTY
,EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS_QTY
,FOLLOWS_QTY
,FULL_SCREEN_PLAYS_QTY
,IMPRESSIONS_QTY
,JOB_APPLICATIONS_QTY
,JOB_APPLY_CLICKS_QTY
,LANDING_PAGE_CLICKS_QTY
,LEAD_GENERATION_MAIL_CONTACT_INFO_SHARES_QTY
,LEAD_GENERATION_MAIL_INTERESTED_CLICKS_QTY
,LIKES_QTY
,ONE_CLICK_LEADS_QTY
,ONE_CLICK_LEAD_FORM_OPENS_QTY
,OPENS_QTY
,OTHER_ENGAGEMENTS_QTY
,POST_CLICK_JOB_APPLICATIONS_QTY
,POST_CLICK_JOB_APPLY_CLICKS_QTY
,POST_CLICK_REGISTRATIONS_QTY
,POST_VIEW_JOB_APPLICATIONS_QTY
,POST_VIEW_JOB_APPLY_CLICKS_QTY
,POST_VIEW_REGISTRATIONS_QTY
,REACTIONS_QTY
,REGISTRATIONS_QTY
,SENDS_QTY
,SHARES_QTY
,TALENT_LEADS_QTY
,TEXT_URL_CLICKS_QTY
,TOTAL_ENGAGEMENTS_QTY
,VIDEO_COMPLETIONS_QTY
,VIDEO_FIRST_QUARTILE_COMPLETIONS_QTY
,VIDEO_MIDPOINT_COMPLETIONS_QTY
,VIDEO_STARTS_QTY
,VIDEO_THIRD_QUARTILE_COMPLETIONS_QTY
,VIDEO_VIEWS_QTY
,VIRAL_CARD_CLICKS_QTY
,VIRAL_CARD_IMPRESSIONS_QTY
,VIRAL_CLICKS_QTY
,VIRAL_COMMENTS_QTY
,VIRAL_COMMENT_LIKES_QTY
,VIRAL_COMPANY_PAGE_CLICKS_QTY
,VIRAL_DOCUMENT_COMPLETIONS_QTY
,VIRAL_DOCUMENT_FIRST_QUARTILE_COMPLETIONS_QTY
,VIRAL_DOCUMENT_MIDPOINT_COMPLETIONS_QTY
,VIRAL_DOCUMENT_THIRD_QUARTILE_COMPLETIONS_QTY
,VIRAL_DOWNLOAD_CLICKS_QTY
,VIRAL_EXTERNAL_WEBSITE_CONVERSIONS_QTY
,VIRAL_EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS_QTY
,VIRAL_EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS_QTY
,VIRAL_FOLLOWS_QTY
,VIRAL_FULL_SCREEN_PLAYS_QTY
,VIRAL_IMPRESSIONS_QTY
,VIRAL_JOB_APPLICATIONS_QTY
,VIRAL_JOB_APPLY_CLICKS_QTY
,VIRAL_LANDING_PAGE_CLICKS_QTY
,VIRAL_LIKES_QTY
,VIRAL_ONE_CLICK_LEADS_QTY
,VIRAL_ONE_CLICK_LEAD_FORM_OPENS_QTY
,VIRAL_OTHER_ENGAGEMENTS_QTY
,VIRAL_POST_CLICK_JOB_APPLICATIONS_QTY
,VIRAL_POST_CLICK_JOB_APPLY_CLICKS_QTY
,VIRAL_POST_CLICK_REGISTRATIONS_QTY
,VIRAL_POST_VIEW_JOB_APPLICATIONS_QTY
,VIRAL_POST_VIEW_JOB_APPLY_CLICKS_QTY
,VIRAL_POST_VIEW_REGISTRATIONS_QTY
,VIRAL_REACTIONS_QTY
,VIRAL_REGISTRATIONS_QTY
,VIRAL_SHARES_QTY
,VIRAL_TOTAL_ENGAGEMENTS_QTY
,VIRAL_VIDEO_COMPLETIONS_QTY
,VIRAL_VIDEO_FIRST_QUARTILE_COMPLETIONS_QTY
,VIRAL_VIDEO_MIDPOINT_COMPLETIONS_QTY
,VIRAL_VIDEO_STARTS_QTY
,VIRAL_VIDEO_THIRD_QUARTILE_COMPLETIONS_QTY
,VIRAL_VIDEO_VIEWS_QTY
FROM SRC_ADS_CAMPAIGN;

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.LINKEDIN.VW_LINKEDIN_FS_ADS_ANALYTICS_BY_CREATIVE AS

WITH SRC_ADS_CREATIVE AS
(SELECT
  CREATIVE_ID                                               AS CREATIVE_ID
 ,CREATIVE                                                  AS CREATIVE_DC
 ,TO_TIMESTAMP_NTZ(LEFT(START_AT,LEN(START_AT) -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS START_AT_DTTM
 ,TO_TIMESTAMP_NTZ(LEFT(  END_AT,LEN(END_AT  ) -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS END_AT_DTTM
 ,DATE_RANGE::VARCHAR(200000)                               AS DATE_RANGE_ARRAY
 ,PIVOT_VALUES::VARCHAR(200000)                             AS PIVOT_VALUES_ARRAY
 ,PIVOT                                                     AS PIVOT_DC
 ,PIVOT_VALUE                                               AS PIVOT_VALUE_DC
 ,ACTION_CLICKS                                             AS ACTION_CLICKS_QTY
 ,AD_UNIT_CLICKS                                            AS AD_UNIT_CLICKS_QTY
 ,APPROXIMATE_UNIQUE_IMPRESSIONS                            AS APPROXIMATE_UNIQUE_IMPRESSIONS_QTY
 ,CARD_CLICKS                                               AS CARD_CLICKS_QTY
 ,CARD_IMPRESSIONS                                          AS CARD_IMPRESSIONS_QTY
 ,CLICKS                                                    AS CLICKS_QTY
 ,COMMENTS                                                  AS COMMENTS_QTY
 ,COMMENT_LIKES                                             AS COMMENT_LIKES_QTY
 ,COMPANY_PAGE_CLICKS                                       AS COMPANY_PAGE_CLICKS_QTY
 ,CONVERSION_VALUE_IN_LOCAL_CURRENCY                        AS CONVERSION_VALUE_IN_LOCAL_CURRENCY_AMT
 ,COST_IN_LOCAL_CURRENCY                                    AS COST_IN_LOCAL_CURRENCY_AMT
 ,COST_IN_USD                                               AS COST_IN_USD_AMT
 ,DOCUMENT_COMPLETIONS                                      AS DOCUMENT_COMPLETIONS_QTY
 ,DOCUMENT_FIRST_QUARTILE_COMPLETIONS                       AS DOCUMENT_FIRST_QUARTILE_COMPLETIONS_QTY
 ,DOCUMENT_MIDPOINT_COMPLETIONS                             AS DOCUMENT_MIDPOINT_COMPLETIONS_QTY
 ,DOCUMENT_THIRD_QUARTILE_COMPLETIONS                       AS DOCUMENT_THIRD_QUARTILE_COMPLETIONS_QTY
 ,DOWNLOAD_CLICKS                                           AS DOWNLOAD_CLICKS_QTY
 ,EXTERNAL_WEBSITE_CONVERSIONS                              AS EXTERNAL_WEBSITE_CONVERSIONS_QTY
 ,EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS                   AS EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS_QTY
 ,EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS                    AS EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS_QTY
 ,FOLLOWS                                                   AS FOLLOWS_QTY
 ,FULL_SCREEN_PLAYS                                         AS FULL_SCREEN_PLAYS_QTY
 ,IMPRESSIONS                                               AS IMPRESSIONS_QTY
 ,JOB_APPLICATIONS                                          AS JOB_APPLICATIONS_QTY
 ,JOB_APPLY_CLICKS                                          AS JOB_APPLY_CLICKS_QTY
 ,LANDING_PAGE_CLICKS                                       AS LANDING_PAGE_CLICKS_QTY
 ,LEAD_GENERATION_MAIL_CONTACT_INFO_SHARES                  AS LEAD_GENERATION_MAIL_CONTACT_INFO_SHARES_QTY
 ,LEAD_GENERATION_MAIL_INTERESTED_CLICKS                    AS LEAD_GENERATION_MAIL_INTERESTED_CLICKS_QTY
 ,LIKES                                                     AS LIKES_QTY
 ,ONE_CLICK_LEADS                                           AS ONE_CLICK_LEADS_QTY
 ,ONE_CLICK_LEAD_FORM_OPENS                                 AS ONE_CLICK_LEAD_FORM_OPENS_QTY
 ,OPENS                                                     AS OPENS_QTY
 ,OTHER_ENGAGEMENTS                                         AS OTHER_ENGAGEMENTS_QTY
 ,POST_CLICK_JOB_APPLICATIONS                               AS POST_CLICK_JOB_APPLICATIONS_QTY
 ,POST_CLICK_JOB_APPLY_CLICKS                               AS POST_CLICK_JOB_APPLY_CLICKS_QTY
 ,POST_CLICK_REGISTRATIONS                                  AS POST_CLICK_REGISTRATIONS_QTY
 ,POST_VIEW_JOB_APPLICATIONS                                AS POST_VIEW_JOB_APPLICATIONS_QTY
 ,POST_VIEW_JOB_APPLY_CLICKS                                AS POST_VIEW_JOB_APPLY_CLICKS_QTY
 ,POST_VIEW_REGISTRATIONS                                   AS POST_VIEW_REGISTRATIONS_QTY
 ,REACTIONS                                                 AS REACTIONS_QTY
 ,REGISTRATIONS                                             AS REGISTRATIONS_QTY
 ,SENDS                                                     AS SENDS_QTY
 ,SHARES                                                    AS SHARES_QTY
 ,TALENT_LEADS                                              AS TALENT_LEADS_QTY
 ,TEXT_URL_CLICKS                                           AS TEXT_URL_CLICKS_QTY
 ,TOTAL_ENGAGEMENTS                                         AS TOTAL_ENGAGEMENTS_QTY
 ,VIDEO_COMPLETIONS                                         AS VIDEO_COMPLETIONS_QTY
 ,VIDEO_FIRST_QUARTILE_COMPLETIONS                          AS VIDEO_FIRST_QUARTILE_COMPLETIONS_QTY
 ,VIDEO_MIDPOINT_COMPLETIONS                                AS VIDEO_MIDPOINT_COMPLETIONS_QTY
 ,VIDEO_STARTS                                              AS VIDEO_STARTS_QTY
 ,VIDEO_THIRD_QUARTILE_COMPLETIONS                          AS VIDEO_THIRD_QUARTILE_COMPLETIONS_QTY
 ,VIDEO_VIEWS                                               AS VIDEO_VIEWS_QTY
 ,VIRAL_CARD_CLICKS                                         AS VIRAL_CARD_CLICKS_QTY
 ,VIRAL_CARD_IMPRESSIONS                                    AS VIRAL_CARD_IMPRESSIONS_QTY
 ,VIRAL_CLICKS                                              AS VIRAL_CLICKS_QTY
 ,VIRAL_COMMENTS                                            AS VIRAL_COMMENTS_QTY
 ,VIRAL_COMMENT_LIKES                                       AS VIRAL_COMMENT_LIKES_QTY
 ,VIRAL_COMPANY_PAGE_CLICKS                                 AS VIRAL_COMPANY_PAGE_CLICKS_QTY
 ,VIRAL_DOCUMENT_COMPLETIONS                                AS VIRAL_DOCUMENT_COMPLETIONS_QTY
 ,VIRAL_DOCUMENT_FIRST_QUARTILE_COMPLETIONS                 AS VIRAL_DOCUMENT_FIRST_QUARTILE_COMPLETIONS_QTY
 ,VIRAL_DOCUMENT_MIDPOINT_COMPLETIONS                       AS VIRAL_DOCUMENT_MIDPOINT_COMPLETIONS_QTY
 ,VIRAL_DOCUMENT_THIRD_QUARTILE_COMPLETIONS                 AS VIRAL_DOCUMENT_THIRD_QUARTILE_COMPLETIONS_QTY
 ,VIRAL_DOWNLOAD_CLICKS                                     AS VIRAL_DOWNLOAD_CLICKS_QTY
 ,VIRAL_EXTERNAL_WEBSITE_CONVERSIONS                        AS VIRAL_EXTERNAL_WEBSITE_CONVERSIONS_QTY
 ,VIRAL_EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS             AS VIRAL_EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS_QTY
 ,VIRAL_EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS              AS VIRAL_EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS_QTY
 ,VIRAL_FOLLOWS                                             AS VIRAL_FOLLOWS_QTY
 ,VIRAL_FULL_SCREEN_PLAYS                                   AS VIRAL_FULL_SCREEN_PLAYS_QTY
 ,VIRAL_IMPRESSIONS                                         AS VIRAL_IMPRESSIONS_QTY
 ,VIRAL_JOB_APPLICATIONS                                    AS VIRAL_JOB_APPLICATIONS_QTY
 ,VIRAL_JOB_APPLY_CLICKS                                    AS VIRAL_JOB_APPLY_CLICKS_QTY
 ,VIRAL_LANDING_PAGE_CLICKS                                 AS VIRAL_LANDING_PAGE_CLICKS_QTY
 ,VIRAL_LIKES                                               AS VIRAL_LIKES_QTY
 ,VIRAL_ONE_CLICK_LEADS                                     AS VIRAL_ONE_CLICK_LEADS_QTY
 ,VIRAL_ONE_CLICK_LEAD_FORM_OPENS                           AS VIRAL_ONE_CLICK_LEAD_FORM_OPENS_QTY
 ,VIRAL_OTHER_ENGAGEMENTS                                   AS VIRAL_OTHER_ENGAGEMENTS_QTY
 ,VIRAL_POST_CLICK_JOB_APPLICATIONS                         AS VIRAL_POST_CLICK_JOB_APPLICATIONS_QTY
 ,VIRAL_POST_CLICK_JOB_APPLY_CLICKS                         AS VIRAL_POST_CLICK_JOB_APPLY_CLICKS_QTY
 ,VIRAL_POST_CLICK_REGISTRATIONS                            AS VIRAL_POST_CLICK_REGISTRATIONS_QTY
 ,VIRAL_POST_VIEW_JOB_APPLICATIONS                          AS VIRAL_POST_VIEW_JOB_APPLICATIONS_QTY
 ,VIRAL_POST_VIEW_JOB_APPLY_CLICKS                          AS VIRAL_POST_VIEW_JOB_APPLY_CLICKS_QTY
 ,VIRAL_POST_VIEW_REGISTRATIONS                             AS VIRAL_POST_VIEW_REGISTRATIONS_QTY
 ,VIRAL_REACTIONS                                           AS VIRAL_REACTIONS_QTY
 ,VIRAL_REGISTRATIONS                                       AS VIRAL_REGISTRATIONS_QTY
 ,VIRAL_SHARES                                              AS VIRAL_SHARES_QTY
 ,VIRAL_TOTAL_ENGAGEMENTS                                   AS VIRAL_TOTAL_ENGAGEMENTS_QTY
 ,VIRAL_VIDEO_COMPLETIONS                                   AS VIRAL_VIDEO_COMPLETIONS_QTY
 ,VIRAL_VIDEO_FIRST_QUARTILE_COMPLETIONS                    AS VIRAL_VIDEO_FIRST_QUARTILE_COMPLETIONS_QTY
 ,VIRAL_VIDEO_MIDPOINT_COMPLETIONS                          AS VIRAL_VIDEO_MIDPOINT_COMPLETIONS_QTY
 ,VIRAL_VIDEO_STARTS                                        AS VIRAL_VIDEO_STARTS_QTY
 ,VIRAL_VIDEO_THIRD_QUARTILE_COMPLETIONS                    AS VIRAL_VIDEO_THIRD_QUARTILE_COMPLETIONS_QTY
 ,VIRAL_VIDEO_VIEWS                                         AS VIRAL_VIDEO_VIEWS_QTY
FROM LINKEDIN.AD_ANALYTICS_BY_CREATIVE
)

SELECT
 CREATIVE_ID
,CREATIVE_DC
,START_AT_DTTM
,END_AT_DTTM
,DATE_RANGE_ARRAY
,PIVOT_VALUES_ARRAY
,PIVOT_DC
,PIVOT_VALUE_DC
,ACTION_CLICKS_QTY
,AD_UNIT_CLICKS_QTY
,APPROXIMATE_UNIQUE_IMPRESSIONS_QTY
,CARD_CLICKS_QTY
,CARD_IMPRESSIONS_QTY
,CLICKS_QTY
,COMMENTS_QTY
,COMMENT_LIKES_QTY
,COMPANY_PAGE_CLICKS_QTY
,CONVERSION_VALUE_IN_LOCAL_CURRENCY_AMT
,COST_IN_LOCAL_CURRENCY_AMT
,COST_IN_USD_AMT
,DOCUMENT_COMPLETIONS_QTY
,DOCUMENT_FIRST_QUARTILE_COMPLETIONS_QTY
,DOCUMENT_MIDPOINT_COMPLETIONS_QTY
,DOCUMENT_THIRD_QUARTILE_COMPLETIONS_QTY
,DOWNLOAD_CLICKS_QTY
,EXTERNAL_WEBSITE_CONVERSIONS_QTY
,EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS_QTY
,EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS_QTY
,FOLLOWS_QTY
,FULL_SCREEN_PLAYS_QTY
,IMPRESSIONS_QTY
,JOB_APPLICATIONS_QTY
,JOB_APPLY_CLICKS_QTY
,LANDING_PAGE_CLICKS_QTY
,LEAD_GENERATION_MAIL_CONTACT_INFO_SHARES_QTY
,LEAD_GENERATION_MAIL_INTERESTED_CLICKS_QTY
,LIKES_QTY
,ONE_CLICK_LEADS_QTY
,ONE_CLICK_LEAD_FORM_OPENS_QTY
,OPENS_QTY
,OTHER_ENGAGEMENTS_QTY
,POST_CLICK_JOB_APPLICATIONS_QTY
,POST_CLICK_JOB_APPLY_CLICKS_QTY
,POST_CLICK_REGISTRATIONS_QTY
,POST_VIEW_JOB_APPLICATIONS_QTY
,POST_VIEW_JOB_APPLY_CLICKS_QTY
,POST_VIEW_REGISTRATIONS_QTY
,REACTIONS_QTY
,REGISTRATIONS_QTY
,SENDS_QTY
,SHARES_QTY
,TALENT_LEADS_QTY
,TEXT_URL_CLICKS_QTY
,TOTAL_ENGAGEMENTS_QTY
,VIDEO_COMPLETIONS_QTY
,VIDEO_FIRST_QUARTILE_COMPLETIONS_QTY
,VIDEO_MIDPOINT_COMPLETIONS_QTY
,VIDEO_STARTS_QTY
,VIDEO_THIRD_QUARTILE_COMPLETIONS_QTY
,VIDEO_VIEWS_QTY
,VIRAL_CARD_CLICKS_QTY
,VIRAL_CARD_IMPRESSIONS_QTY
,VIRAL_CLICKS_QTY
,VIRAL_COMMENTS_QTY
,VIRAL_COMMENT_LIKES_QTY
,VIRAL_COMPANY_PAGE_CLICKS_QTY
,VIRAL_DOCUMENT_COMPLETIONS_QTY
,VIRAL_DOCUMENT_FIRST_QUARTILE_COMPLETIONS_QTY
,VIRAL_DOCUMENT_MIDPOINT_COMPLETIONS_QTY
,VIRAL_DOCUMENT_THIRD_QUARTILE_COMPLETIONS_QTY
,VIRAL_DOWNLOAD_CLICKS_QTY
,VIRAL_EXTERNAL_WEBSITE_CONVERSIONS_QTY
,VIRAL_EXTERNAL_WEBSITE_POST_CLICK_CONVERSIONS_QTY
,VIRAL_EXTERNAL_WEBSITE_POST_VIEW_CONVERSIONS_QTY
,VIRAL_FOLLOWS_QTY
,VIRAL_FULL_SCREEN_PLAYS_QTY
,VIRAL_IMPRESSIONS_QTY
,VIRAL_JOB_APPLICATIONS_QTY
,VIRAL_JOB_APPLY_CLICKS_QTY
,VIRAL_LANDING_PAGE_CLICKS_QTY
,VIRAL_LIKES_QTY
,VIRAL_ONE_CLICK_LEADS_QTY
,VIRAL_ONE_CLICK_LEAD_FORM_OPENS_QTY
,VIRAL_OTHER_ENGAGEMENTS_QTY
,VIRAL_POST_CLICK_JOB_APPLICATIONS_QTY
,VIRAL_POST_CLICK_JOB_APPLY_CLICKS_QTY
,VIRAL_POST_CLICK_REGISTRATIONS_QTY
,VIRAL_POST_VIEW_JOB_APPLICATIONS_QTY
,VIRAL_POST_VIEW_JOB_APPLY_CLICKS_QTY
,VIRAL_POST_VIEW_REGISTRATIONS_QTY
,VIRAL_REACTIONS_QTY
,VIRAL_REGISTRATIONS_QTY
,VIRAL_SHARES_QTY
,VIRAL_TOTAL_ENGAGEMENTS_QTY
,VIRAL_VIDEO_COMPLETIONS_QTY
,VIRAL_VIDEO_FIRST_QUARTILE_COMPLETIONS_QTY
,VIRAL_VIDEO_MIDPOINT_COMPLETIONS_QTY
,VIRAL_VIDEO_STARTS_QTY
,VIRAL_VIDEO_THIRD_QUARTILE_COMPLETIONS_QTY
,VIRAL_VIDEO_VIEWS_QTY
FROM SRC_ADS_CREATIVE;

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.TIKTOK_ADS.VW_FS_ADS_INSIGHTS_AGE_AND_GENDER AS

WITH SRC_ADS_AG AS
(SELECT DISTINCT
  ADGROUP_ID                    AS ADGROUP_ID
 ,ADGROUP_NAME                  AS ADGROUP_NM
 ,ADVERTISER_ID                 AS ADVERTISER_ID
 ,AD_ID                         AS AD_ID
 ,AD_NAME                       AS AD_NM
 ,AD_TEXT                       AS AD_TXT
 ,AGE                           AS AGE_DC
 ,CAMPAIGN_ID                   AS CAMPAIGN_ID
 ,CAMPAIGN_NAME                 AS CAMPAIGN_NM
 ,GENDER                        AS GENDER_DC
 ,DPA_TARGET_AUDIENCE_TYPE      AS DPA_TARGET_AUDIENCE_TYPE_DC
 ,TO_TIMESTAMP_NTZ(LEFT(STAT_TIME_DAY,LEN(STAT_TIME_DAY) -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS STAT_DTTM
 ,IMPRESSIONS                   AS IMPRESSIONS_QTY
 ,CONVERSION                    AS CONVERSION_QTY
 ,CONVERSION_RATE               AS CONVERTION_PCT
 ,MOBILE_APP_ID                 AS MOBILE_APP_ID
 ,PROMOTION_TYPE                AS PROMOTION_TYPE_DC
 ,TT_APP_ID                     AS TIKTOK_APP_ID
 ,TT_APP_NAME                   AS TIKTOK_APP_NM
 ,CLICKS                        AS CLICK_QTY
 ,COST_PER_CONVERSION           AS COST_PER_CONVERSION_AMT
 ,COST_PER_RESULT               AS COST_PRE_RESULT_AMT
 ,CPC                           AS COST_PER_CLICK_AMT
 ,CPM                           AS COST_PER_THOUSAND_IMPRESSIONS_AMT
 ,CTR                           AS CLICK_THROUGH_PCT
 ,REAL_TIME_CONVERSION          AS REAL_TIME_CONVERSION_QTY
 ,REAL_TIME_CONVERSION_RATE     AS REAL_TIME_CONVERSION_PCT
 ,REAL_TIME_COST_PER_CONVERSION AS REAL_TIME_COST_PER_CONVERSION_AMT
 ,REAL_TIME_COST_PER_RESULT     AS REAL_TIME_COST_PER_RESULT_AMT
 ,REAL_TIME_RESULT              AS REAL_TIME_RESULT_QTY
 ,REAL_TIME_RESULT_RATE         AS REAL_TIME_RESULT_PCT
 ,RESULT                        AS RESULT_QTY
 ,RESULT_RATE                   AS RESULT_PCT
 ,SPEND                         AS SPEND_AMT
FROM TIKTOK_ADS.AD_INSIGHTS_BY_AGE_AND_GENDER
)

SELECT
 ADGROUP_ID
,ADGROUP_NM
,ADVERTISER_ID
,AD_ID
,AD_NM
,AD_TXT
,AGE_DC
,CAMPAIGN_ID
,CAMPAIGN_NM
,GENDER_DC
,DPA_TARGET_AUDIENCE_TYPE_DC
,STAT_DTTM
,IMPRESSIONS_QTY
,CONVERSION_QTY
,CONVERTION_PCT
,MOBILE_APP_ID
,PROMOTION_TYPE_DC
,TIKTOK_APP_ID
,TIKTOK_APP_NM
,CLICK_QTY
,COST_PER_CONVERSION_AMT
,COST_PRE_RESULT_AMT
,COST_PER_CLICK_AMT
,COST_PER_THOUSAND_IMPRESSIONS_AMT
,CLICK_THROUGH_PCT
,REAL_TIME_CONVERSION_QTY
,REAL_TIME_CONVERSION_PCT
,REAL_TIME_COST_PER_CONVERSION_AMT
,REAL_TIME_COST_PER_RESULT_AMT
,REAL_TIME_RESULT_QTY
,REAL_TIME_RESULT_PCT
,RESULT_QTY
,RESULT_PCT
,SPEND_AMT
FROM SRC_ADS_AG;

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.TIKTOK_ADS.VW_FS_ADS_INSIGHTS_COUNTRY AS

WITH SRC_ADS_COUNTRY AS
(SELECT DISTINCT
  ADGROUP_ID                    AS ADGROUP_ID
 ,ADGROUP_NAME                  AS ADGROUP_NM
 ,ADVERTISER_ID                 AS ADVERTISER_ID
 ,AD_ID                         AS AD_ID
 ,AD_NAME                       AS AD_NM
 ,AD_TEXT                       AS AD_TXT
 ,CAMPAIGN_ID                   AS CAMPAIGN_ID
 ,CAMPAIGN_NAME                 AS CAMPAIGN_NM
 ,DPA_TARGET_AUDIENCE_TYPE      AS DPA_TARGET_AUDIENCE_TYPE_DC
 ,COUNTRY_CODE                  AS COUNTRY_CD
 ,TO_TIMESTAMP_NTZ(LEFT(STAT_TIME_DAY,LEN(STAT_TIME_DAY) -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS STAT_DTTM
 ,IMPRESSIONS                   AS IMPRESSIONS_QTY
 ,CONVERSION                    AS CONVERSION_QTY
 ,CONVERSION_RATE               AS CONVERTION_PCT
 ,MOBILE_APP_ID                 AS MOBILE_APP_ID
 ,PROMOTION_TYPE                AS PROMOTION_TYPE_DC
 ,TT_APP_ID                     AS TIKTOK_APP_ID
 ,TT_APP_NAME                   AS TIKTOK_APP_NM
 ,CLICKS                        AS CLICK_QTY
 ,COST_PER_CONVERSION           AS COST_PER_CONVERSION_AMT
 ,COST_PER_RESULT               AS COST_PRE_RESULT_AMT
 ,CPC                           AS COST_PER_CLICK_AMT
 ,CPM                           AS COST_PER_THOUSAND_IMPRESSIONS_AMT
 ,CTR                           AS CLICK_THROUGH_PCT
 ,REAL_TIME_CONVERSION          AS REAL_TIME_CONVERSION_QTY
 ,REAL_TIME_CONVERSION_RATE     AS REAL_TIME_CONVERSION_PCT
 ,REAL_TIME_COST_PER_CONVERSION AS REAL_TIME_COST_PER_CONVERSION_AMT
 ,REAL_TIME_COST_PER_RESULT     AS REAL_TIME_COST_PER_RESULT_AMT
 ,REAL_TIME_RESULT              AS REAL_TIME_RESULT_QTY
 ,REAL_TIME_RESULT_RATE         AS REAL_TIME_RESULT_PCT
 ,RESULT                        AS RESULT_QTY
 ,RESULT_RATE                   AS RESULT_PCT
 ,SPEND                         AS SPEND_AMT
FROM TIKTOK_ADS.AD_INSIGHTS_BY_COUNTRY
)

SELECT
 ADGROUP_ID
,ADGROUP_NM
,ADVERTISER_ID
,AD_ID
,AD_NM
,AD_TXT
,CAMPAIGN_ID
,CAMPAIGN_NM
,DPA_TARGET_AUDIENCE_TYPE_DC
,COUNTRY_CD
,STAT_DTTM
,IMPRESSIONS_QTY
,CONVERSION_QTY
,CONVERTION_PCT
,MOBILE_APP_ID
,PROMOTION_TYPE_DC
,TIKTOK_APP_ID
,TIKTOK_APP_NM
,CLICK_QTY
,COST_PER_CONVERSION_AMT
,COST_PRE_RESULT_AMT
,COST_PER_CLICK_AMT
,COST_PER_THOUSAND_IMPRESSIONS_AMT
,CLICK_THROUGH_PCT
,REAL_TIME_CONVERSION_QTY
,REAL_TIME_CONVERSION_PCT
,REAL_TIME_COST_PER_CONVERSION_AMT
,REAL_TIME_COST_PER_RESULT_AMT
,REAL_TIME_RESULT_QTY
,REAL_TIME_RESULT_PCT
,RESULT_QTY
,RESULT_PCT
,SPEND_AMT
FROM SRC_ADS_COUNTRY;

--##############################################################################
CREATE OR REPLACE VIEW ADDATAFUSION.TIKTOK_ADS.VW_FS_ADS_INSIGHTS_PLATFORM AS

WITH SRC_ADS_PLATFORM AS
(SELECT DISTINCT
  ADGROUP_ID                    AS ADGROUP_ID
 ,ADGROUP_NAME                  AS ADGROUP_NM
 ,ADVERTISER_ID                 AS ADVERTISER_ID
 ,AD_ID                         AS AD_ID
 ,AD_NAME                       AS AD_NM
 ,AD_TEXT                       AS AD_TXT
 ,CAMPAIGN_ID                   AS CAMPAIGN_ID
 ,CAMPAIGN_NAME                 AS CAMPAIGN_NM
 ,DPA_TARGET_AUDIENCE_TYPE      AS DPA_TARGET_AUDIENCE_TYPE_DC
 ,PLATFORM                      AS PLATFORM_DC
 ,TO_TIMESTAMP_NTZ(LEFT(STAT_TIME_DAY,LEN(STAT_TIME_DAY) -4), 'YYYY-MM-DD HH24:MI:SS.FF') AS STAT_DTTM
 ,IMPRESSIONS                   AS IMPRESSIONS_QTY
 ,CONVERSION                    AS CONVERSION_QTY
 ,CONVERSION_RATE               AS CONVERTION_PCT
 ,MOBILE_APP_ID                 AS MOBILE_APP_ID
 ,PROMOTION_TYPE                AS PROMOTION_TYPE_DC
 ,TT_APP_ID                     AS TIKTOK_APP_ID
 ,TT_APP_NAME                   AS TIKTOK_APP_NM
 ,CLICKS                        AS CLICK_QTY
 ,COST_PER_CONVERSION           AS COST_PER_CONVERSION_AMT
 ,COST_PER_RESULT               AS COST_PRE_RESULT_AMT
 ,CPC                           AS COST_PER_CLICK_AMT
 ,CPM                           AS COST_PER_THOUSAND_IMPRESSIONS_AMT
 ,CTR                           AS CLICK_THROUGH_PCT
 ,REAL_TIME_CONVERSION          AS REAL_TIME_CONVERSION_QTY
 ,REAL_TIME_CONVERSION_RATE     AS REAL_TIME_CONVERSION_PCT
 ,REAL_TIME_COST_PER_CONVERSION AS REAL_TIME_COST_PER_CONVERSION_AMT
 ,REAL_TIME_COST_PER_RESULT     AS REAL_TIME_COST_PER_RESULT_AMT
 ,REAL_TIME_RESULT              AS REAL_TIME_RESULT_QTY
 ,REAL_TIME_RESULT_RATE         AS REAL_TIME_RESULT_PCT
 ,RESULT                        AS RESULT_QTY
 ,RESULT_RATE                   AS RESULT_PCT
 ,SPEND                         AS SPEND_AMT
FROM TIKTOK_ADS.AD_INSIGHTS_BY_PLATFORM
)

SELECT
 ADGROUP_ID
,ADGROUP_NM
,ADVERTISER_ID
,AD_ID
,AD_NM
,AD_TXT
,CAMPAIGN_ID
,CAMPAIGN_NM
,DPA_TARGET_AUDIENCE_TYPE_DC
,PLATFORM_DC
,STAT_DTTM
,IMPRESSIONS_QTY
,CONVERSION_QTY
,CONVERTION_PCT
,MOBILE_APP_ID
,PROMOTION_TYPE_DC
,TIKTOK_APP_ID
,TIKTOK_APP_NM
,CLICK_QTY
,COST_PER_CONVERSION_AMT
,COST_PRE_RESULT_AMT
,COST_PER_CLICK_AMT
,COST_PER_THOUSAND_IMPRESSIONS_AMT
,CLICK_THROUGH_PCT
,REAL_TIME_CONVERSION_QTY
,REAL_TIME_CONVERSION_PCT
,REAL_TIME_COST_PER_CONVERSION_AMT
,REAL_TIME_COST_PER_RESULT_AMT
,REAL_TIME_RESULT_QTY
,REAL_TIME_RESULT_PCT
,RESULT_QTY
,RESULT_PCT
,SPEND_AMT
FROM SRC_ADS_PLATFORM;
